const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const {createLibraryStore}=require('../../electron/database'),core=require('../../electron/library-core');
const {launch,sleep}=require('./driver.cjs');
process.env.PIGEON_E2E_HEADLESS='1';process.env.PIGEON_SEMANTIC_PYTHON=path.resolve('.semantic-runtime/bin/python');
(async()=>{const root=path.resolve('.semantic-runtime-logs/ui-smoke'),profile=path.join(root,'profile'),reportDir=path.join(root,'report');await fs.rm(root,{recursive:true,force:true});await fs.mkdir(profile,{recursive:true});await fs.mkdir(reportDir,{recursive:true});await fs.writeFile(path.join(profile,'.pigeon-e2e-profile'),'pigeon-e2e-v1\n');
const note=path.join(root,'birds.txt');await fs.writeFile(note,'Pigeons fly over rooftops. A pigeon is a bird nesting in buildings.');
const files=[['notes','document',note],['image','image',path.resolve('pigeon-logo.png')],['video','video',path.resolve('tests/fixtures/sample-video.mp4')],['audio','audio',path.resolve('tests/fixtures/sample-audio.wav')]];
const assets=[];for(const[id,kind,file]of files){const stat=await fs.stat(file);assets.push({id,kind,path:file,name:path.basename(file),filename:path.basename(file),extension:path.extname(file).slice(1).toUpperCase(),size:stat.size,modified:stat.mtimeMs,locationId:'file-'+id,tags:[],collectionIds:[],thumbnailPath:path.resolve('pigeon-logo.png')});}
const secret=path.join(root,'secret.txt');await fs.copyFile(note,secret);const secretStat=await fs.stat(secret);assets.push({...assets[0],id:'locked',locationId:'file-locked',path:secret,name:'secret.txt',filename:'secret.txt',modified:secretStat.mtimeMs,collectionIds:['secret']});
const store=createLibraryStore(path.join(profile,'library.db'));store.save(core.migrateLibrary({loading:false,settings:{indexingPolicyVersion:2,autoTag:false,autoImportEnabled:false},locations:assets.map(a=>({id:a.locationId,type:'file',name:a.name,path:a.path,online:true,lastScanned:Date.now()})),assets,collections:[{id:'secret',name:'Locked',lock:{enabled:true,salt:'secret',hash:'secret'}}]}));store.close();
let app;try{app=await launch(profile,reportDir);await app.wait(`typeof state!=='undefined'&&!state.library.loading&&state.library.assets.length>=4`,10000);await app.evaluate(`window.__batchSizes=[];window.pigeon.onSemanticStatus(s=>{if(s.activeFiles?.length)window.__batchSizes.push(s.activeFiles.length)});document.querySelector('#semantic-search-button').click()`);await app.wait(`!document.querySelector('#semantic-panel').classList.contains('hidden')`,5000);await app.evaluate(`window.__semanticStart=null;void window.pigeon.semanticStart().then(s=>window.__semanticStart=s).catch(e=>window.__semanticStart={error:e.message})`);await app.wait(`window.__semanticStart`,30000);assert.equal((await app.evaluate('window.__semanticStart')).error||'','');
await app.wait(`document.querySelector('#semantic-state').textContent.includes('4 indexed')`,180000);assert.equal(await app.evaluate("document.querySelector('[data-semantic=setup]')===null&&document.querySelector('#semantic-dialog')===null"),true);await app.screenshot('semantic-indexed');
await app.evaluate(`document.querySelector('#semantic-query').value='pigeons flying over rooftops';document.querySelector('#semantic-minimum').value='0';document.querySelector('#semantic-form').requestSubmit()`);await app.wait(`state.view==='semantic'&&document.querySelectorAll('#asset-grid .asset-card').length===4`,60000);await app.evaluate(`window.__libraryCount=state.library.assets.length;state.library.assets.push(...Array.from({length:1100},(_,i)=>({id:'unmatched-'+i,kind:'image',name:'Unmatched '+i,path:'/unmatched/'+i,extension:'PNG',tags:[],collectionIds:[]})));invalidateAssetViewCache();renderGrid()`);assert.equal(await app.evaluate("document.querySelectorAll('#asset-grid .asset-card').length"),4,'large portfolios retain semantic ranking and exclude unmatched assets');await app.evaluate(`state.library.assets.splice(window.__libraryCount);invalidateAssetViewCache();renderGrid();document.querySelector('#semantic-minimum').dispatchEvent(new Event('input'))`);await app.screenshot('semantic-results');assert.ok(await app.evaluate(`document.querySelector('#semantic-resource').textContent.includes('Kernel limits active')`));
await app.evaluate(`document.querySelector('#asset-grid .asset-card').click()`);assert.ok(await app.evaluate('Boolean(state.selectedId)'));await app.evaluate(`document.querySelector('#right-panel-details-tab').click()`);assert.ok(await app.evaluate("!document.querySelector('#inspector-details-panel').classList.contains('hidden')"));await app.evaluate(`document.querySelector('#right-panel-semantic-tab').click()`);const resources=await app.evaluate(`window.pigeon.semanticStatus()`);assert.ok(resources.hardCaps);assert.equal(resources.limited,0);assert.equal(resources.indexed,4);assert.ok(await app.evaluate('window.__batchSizes.some(n=>n>1)'), 'multiple files are analyzed in the same real-model batch');
await app.evaluate(`window.__sampleResult=null;void window.pigeon.semanticSearch({assetId:'image',minimum:0}).then(r=>window.__sampleResult=r).catch(e=>window.__sampleResult={error:e.message})`);await app.wait('window.__sampleResult',60000);const sample=await app.evaluate('window.__sampleResult');assert.equal(sample.error,undefined);assert.equal(sample.results.length,3);assert.ok(!sample.results.some(r=>r.id==='locked'));
await app.evaluate(`window.__paused=null;void window.pigeon.semanticPause(true).then(s=>window.__paused=s)`);await app.wait('window.__paused');assert.equal((await app.evaluate('window.__paused')).paused,true);await app.evaluate(`window.pigeon.semanticPause(false)`);
await app.evaluate(`window.__configured=null;void window.pigeon.semanticConfigure({automatic:false}).then(s=>window.__configured=s)`);await app.wait('window.__configured');assert.equal((await app.evaluate('window.__configured')).paused,false);await app.evaluate(`window.__afterDisable=null;void window.pigeon.semanticSearch({query:'bird',minimum:0}).then(r=>window.__afterDisable=r).catch(e=>window.__afterDisable={error:e.message})`);await app.wait('window.__afterDisable',30000);assert.equal((await app.evaluate('window.__afterDisable')).results.length,4);await app.evaluate(`window.__other=null;void window.pigeon.createPortfolio('Other semantic test').then(r=>window.__other=r)`);await app.wait('window.__other');await app.evaluate(`window.__switched=null;void window.pigeon.switchPortfolio(window.__other.id).then(r=>window.__switched=true)`);await app.wait('window.__switched',10000);await app.evaluate(`window.__otherStatus=null;void window.pigeon.semanticStatus().then(r=>window.__otherStatus=r)`);await app.wait('window.__otherStatus');assert.equal((await app.evaluate('window.__otherStatus')).indexed,0);assert.equal(app.errors.length,0,JSON.stringify(app.errors));await fs.writeFile(path.join(reportDir,'report.json'),JSON.stringify({status:'passed',cases:['right panel opens without a modal or setup button','native thumbnail results','large portfolio result isolation','selection and Details tab','four real media types indexed','text search','sample image search','locked assets excluded','pause/resume','Linux kernel caps'],resources},null,2));console.log('SEMANTIC UI SMOKE PASSED',root);
}finally{await app?.close();}})().catch(error=>{console.error(error);process.exitCode=1});
