'use strict';
const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
const{createFixtures}=require('./fixtures.cjs'),{launch}=require('./driver.cjs');
process.env.PIGEON_E2E_HEADLESS='1';
(async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'pigeon-toolbar-title-')),report=path.join(root,'report');await fs.mkdir(report);const fixture=await createFixtures(root,{count:180,coldCount:0});let app;
try{app=await launch(fixture.profile,report);await app.wait("document.querySelector('#startup-splash').classList.contains('hidden')&&!state.library.assetStreamPending");
const check=async()=>{await app.wait("document.querySelector('[data-thumbnail-tab=files]').textContent==='▱ '+elements.title.textContent");const value=await app.evaluate(`(()=>{const title=elements.title,tab=document.querySelector('[data-thumbnail-tab=files]'),left=document.querySelector('.toolbar-left'),forward=document.querySelector('#navigation-forward'),back=document.querySelector('#navigation-back');return{title:title.textContent,tab:tab.textContent,titleDisplay:getComputedStyle(title).display,titleWidth:title.getBoundingClientRect().width,leftWidth:left.getBoundingClientRect().width,backWidth:back.getBoundingClientRect().width,forwardWidth:forward.getBoundingClientRect().width,tabGap:tab.getBoundingClientRect().left-forward.getBoundingClientRect().right};})()`);assert.ok(value.title);assert.equal(value.titleDisplay,'none');assert.equal(value.titleWidth,0);assert.equal(value.tab,'▱ '+value.title);assert.ok(value.backWidth>=23&&value.forwardWidth>=23);assert.ok(value.leftWidth<60,'Removed title must not leave a reserved title column');assert.ok(value.tabGap>=0&&value.tabGap<=12);return value;};
const all=await check();await app.click('[data-location-id="cached-root"] .location-root-button');await app.wait("state.locationId==='cached-root'&&elements.title.textContent===state.library.locations.find(location=>location.id==='cached-root').name");const folder=await check();await app.screenshot('folder-title-in-tab');assert.deepEqual(app.errors,[]);await fs.writeFile(path.join(report,'result.json'),JSON.stringify({status:'passed',all,folder},null,2));console.log(report,JSON.stringify({all,folder}));
}finally{await app?.close();}})().catch(error=>{console.error(error);process.exitCode=1});
