const test=require('node:test');const assert=require('node:assert/strict');const rules=require('../src/auto-tag-rules');const core=require('../electron/library-core');
const asset={name:'Travel photo',filename:'Travel photo.jpg',path:'/Pictures/Trips/Travel photo.jpg',kind:'image',extension:'JPG',width:100,height:50,dominantColor:'#417bd5',rating:4};
const custom={autoTagFilename:false,autoTagKind:false,autoTagOrientation:false,autoTagColor:false,autoTagRulesJson:JSON.stringify([{enabled:true,match:'all',conditions:[{field:'path',operator:'contains',value:'/Trips/'},{field:'rating',operator:'gte',value:'4'}],tags:['travel','{folder}','{kind}-{extension}']}])};
test('explicit sources preserve existing local heuristics',()=>assert.deepEqual(rules.generate(asset,{autoTagFilename:true,autoTagColor:true}),core.suggestTags(asset)));
test('filename words and dominant color are disabled by default',()=>assert.deepEqual(rules.generate(asset),['image','landscape']));
test('generation can be disabled automatically without disabling explicit manual runs',()=>{assert.deepEqual(rules.generate(asset,{...custom,autoTagEnabled:false}),[]);assert.deepEqual(rules.generate(asset,{...custom,autoTagEnabled:false},false),['travel','Trips','image-jpg']);});
test('all/any conditions, disabled rules and templates are deterministic',()=>{assert.deepEqual(rules.generate(asset,custom),['travel','Trips','image-jpg']);const config=JSON.parse(custom.autoTagRulesJson);config[0].conditions[1].value=5;assert.deepEqual(rules.generate(asset,{...custom,autoTagRulesJson:config}),[]);config[0].match='any';assert.equal(rules.generate(asset,{...custom,autoTagRulesJson:config}).length,3);config[0].enabled=false;assert.deepEqual(rules.generate(asset,{...custom,autoTagRulesJson:config}),[]);});
test('invalid rule data does not execute code or create unconditional tags',()=>{assert.deepEqual(rules.generate(asset,{...custom,autoTagRulesJson:'invalid'}),[]);assert.deepEqual(rules.generate(asset,{...custom,autoTagRulesJson:[{conditions:[],tags:['bad']}]}),[]);assert.equal(rules.matches(asset,{field:'__proto__',operator:'equals',value:''}),false);assert.equal(rules.matches(asset,{field:'name',operator:'regex',value:'.*'}),false);});
test('tag output deduplicates case-insensitively and caps expansion',()=>{const config={...custom,autoTagRulesJson:[{conditions:[{field:'kind',operator:'equals',value:'IMAGE'}],tags:['Travel','travel',...Array.from({length:90},(_,i)=>'tag'+i)]}]};const result=rules.generate(asset,config);assert.equal(result[0],'Travel');assert.equal(result.filter(tag=>tag.toLowerCase()==='travel').length,1);assert.ok(result.length<=64);});
