const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {DatabaseSync}=require('node:sqlite');
const {collect}=require('../electron/database-telemetry-worker');
const {createDatabaseTelemetry}=require('../electron/database-telemetry');
const {fingerprint}=require('../electron/semantic-policy');
const charts=require('../src/database-telemetry');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'pigeon-inventory-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const databaseFile=path.join(root,'library.db'),other=path.join(root,'other.db'),thumbnailDir=path.join(root,'thumbnails'),source=path.join(root,'source');fs.mkdirSync(path.join(thumbnailDir,'edits'),{recursive:true});fs.mkdirSync(path.join(source,'sub'),{recursive:true});for(const[name,bytes]of [['a.jpg',4],['b.jpg',6],['orphan.jpg',5],['edits/edited.png',7],['edits/edited-base.png',3],['preview.jpg',2]])fs.writeFileSync(path.join(thumbnailDir,name),Buffer.alloc(bytes));const assets=[{id:'a',name:'a',kind:'image',path:path.join(source,'a.jpg'),size:100,modified:1,tags:['bird'],locationId:'source',thumbnailPath:path.join(thumbnailDir,'a.jpg'),editedPath:path.join(thumbnailDir,'edits/edited.png'),editorBaseFor:path.join(thumbnailDir,'edits/edited.png'),editedPreviewPath:path.join(thumbnailDir,'preview.jpg')},{id:'b',name:'b',kind:'document',path:path.join(source,'sub/b.txt'),size:200,modified:2,tags:[],locationId:'source'},{id:'missing',kind:'image',path:path.join(source,'missing.jpg'),sourceMissing:true,thumbnailPath:path.join(thumbnailDir,'missing.jpg')},{id:'locked',kind:'image',path:path.join(source,'locked.jpg')},{id:'trash',kind:'file',path:path.join(source,'trash.bin'),deletedAt:1}];const db=new DatabaseSync(databaseFile);db.exec('CREATE TABLE assets(payload TEXT);CREATE TABLE locations(payload TEXT);CREATE TABLE collections(id TEXT);CREATE TABLE smart_folders(id TEXT)');for(const asset of assets)db.prepare('INSERT INTO assets VALUES(?)').run(JSON.stringify(asset));db.prepare('INSERT INTO locations VALUES(?)').run(JSON.stringify({id:'source',name:'Source',path:source,type:'folder'}));db.exec("INSERT INTO collections VALUES('one');INSERT INTO smart_folders VALUES('one')");db.close();const otherDb=new DatabaseSync(other);otherDb.exec('CREATE TABLE assets(payload TEXT)');otherDb.prepare('INSERT INTO assets VALUES(?)').run(JSON.stringify({thumbnailPath:path.join(thumbnailDir,'b.jpg')}));otherDb.close();const sem=new DatabaseSync(databaseFile+'.semantic.sqlite3');sem.exec('CREATE TABLE assets(id TEXT,fingerprint TEXT,complete INTEGER,error TEXT,metadata_dirty INTEGER);CREATE TABLE vectors(asset_id TEXT,part INTEGER,vector BLOB)');sem.prepare('INSERT INTO assets VALUES(?,?,?,?,?)').run('a',fingerprint(assets[0]),1,'',0);sem.prepare('INSERT INTO assets VALUES(?,?,?,?,?)').run('b','stale',1,'',0);sem.prepare('INSERT INTO vectors VALUES(?,?,?)').run('a',0,Buffer.alloc(12));sem.prepare('INSERT INTO vectors VALUES(?,?,?)').run('a',1,Buffer.alloc(12));sem.close();return{portfolioId:'one',databaseFile,thumbnailDir,portfolioDatabases:[databaseFile,other],excludedIds:['locked'],assets,root,source};}
test('read-only inventory includes file/WAL allocation, vectors, stale and excluded assets, and folder-tree coverage',t=>{const data=fixture(t),before=fs.readFileSync(data.databaseFile),result=collect(data);assert.deepEqual(result.errors,[]);assert.equal(result.main.items,5);assert.equal(result.main.tagged,1);assert.equal(result.main.missingSources,1);assert.equal(result.main.trashed,1);assert.equal(result.main.collections,1);assert.equal(result.main.smartFolders,1);assert.equal(result.main.referencedFileBytes,300);assert.ok(result.main.bytes>0);assert.equal(result.main.bytes,result.main.baseBytes+result.main.walBytes+result.main.shmBytes);assert.equal(result.semantic.eligible,2);assert.equal(result.semantic.indexed,1);assert.equal(result.semantic.pending,1);assert.equal(result.semantic.stale,1);assert.equal(result.semantic.excludedItems,3);assert.equal(result.semantic.percent,50);assert.equal(result.semantic.vectors,2);assert.equal(result.semantic.vectorBytes,24);assert.equal(result.semantic.vectorDimensions,3);assert.equal(result.semantic.metadataVectors,1);assert.equal(result.semantic.contentVectors,1);const tree=result.semantic.folders.find(folder=>folder.scope==='Folder tree');assert.equal(tree.total,2);assert.equal(tree.pending,1);assert.ok(result.semantic.folders.some(folder=>folder.path===path.join(data.source,'sub')&&folder.pending===1));assert.deepEqual(fs.readFileSync(data.databaseFile),before,'inventory must not mutate the library');});
test('shared-cache orphan candidates respect every portfolio and edited-image base/preview references',t=>{const result=collect(fixture(t));assert.equal(result.thumbnails.files,6);assert.equal(result.thumbnails.bytes,27);assert.equal(result.thumbnails.referencedFiles,5);assert.equal(result.thumbnails.unreferencedFiles,1);assert.equal(result.thumbnails.unreferencedBytes,5);assert.equal(result.thumbnails.missingReferences,1);assert.equal(result.thumbnails.auditComplete,true);});
test('metadata-dirty rows are pending even when their full fingerprint and completion flag match',t=>{const data=fixture(t),db=new DatabaseSync(data.databaseFile+'.semantic.sqlite3');db.exec("UPDATE assets SET metadata_dirty=1 WHERE id='a'");db.close();const result=collect(data);assert.equal(result.semantic.indexed,0);assert.equal(result.semantic.pending,2);assert.equal(result.semantic.stale,2);});
test('an unreadable portfolio prevents a complete orphan audit rather than reporting false certainty',t=>{const data=fixture(t),broken=path.join(data.root,'broken.db');fs.writeFileSync(broken,'not SQLite');data.portfolioDatabases.push(broken);const result=collect(data);assert.equal(result.thumbnails.auditComplete,false);assert.ok(result.thumbnails.auditErrors.length);});
test('bounded worker inventory is cached, force-refreshable, and scoped to the active database',async t=>{const data=fixture(t),service=createDatabaseTelemetry({getContext:()=>data});t.after(()=>service.close());const first=await service.get(),cached=await service.get();assert.strictEqual(first,cached);const refreshed=await service.get({force:true});assert.notStrictEqual(refreshed,first);assert.equal(refreshed.portfolioId,'one');data.portfolioId='two';data.databaseFile=path.join(data.root,'new.db');const switched=await service.get();assert.equal(switched.portfolioId,'two');assert.equal(switched.main.exists,false);});
test('inventory worker times out safely without deleting or modifying original files',async t=>{const data=fixture(t),service=createDatabaseTelemetry({getContext:()=>data,timeoutMs:1});t.after(()=>service.close());const result=await service.get();assert.match(result.error,/timed out/);assert.ok(fs.existsSync(data.databaseFile));assert.ok(fs.existsSync(path.join(data.thumbnailDir,'orphan.jpg')));});
test('pie and line charts handle empty and single-sample data, and escape labels',()=>{assert.doesNotMatch(charts.pie('Empty',[]),/NaN|Infinity/);const pie=charts.pie('<script>',[['<img src=x>',3],['Safe',1]]);assert.match(pie,/75\.0%/);assert.doesNotMatch(pie,/<script>|<img src=x>/);const line=charts.line('History',[{value:0}],[['CPU','value']]);assert.match(line,/polyline/);assert.doesNotMatch(line,/NaN|Infinity/);});
