const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../src/renderer.js'),'utf8'),html=fs.readFileSync(path.join(__dirname,'../src/index.html'),'utf8');
function harness(action='tags'){
 const state={library:{activePortfolioId:'portfolio',locations:[],collections:[],smartFolders:[]},view:'all',locationId:'folder',locationSubfolder:'photos',collectionId:null,smartFolderId:null,selectedId:'photo',selectedIds:new Set(['photo']),selectionAnchorId:'photo',similarIds:null,showCheckedOnly:true,includeSubfolderContent:true,kind:'image',query:'nature',filters:{tags:new Set(['travel']),ratings:new Set([5])},gridScrollTop:122};
 const elements={search:{value:'nature'},title:{textContent:'Photos'},gridWrap:{scrollTop:122}};let quit=0,pigeon=0,rendered=0,similarity=0;const context={state,elements,Set,preferences:{doubleEscapeAction:action},window:{pigeon:{quitApp(){quit++;}}},cooperativeAssetView:null,libraryAggregateRevision:0,navigationRenderGeneration:0,navigationReturnState:{view:'favorites'},navigationForwardState:{view:'recent'},pigeonTaggedReturnState:{view:'all'},assetViewSignature:()=>'',hideInternalViewer(){},clearInlinePasswordDraft(){},resetRenderLimit(){},updateFilterChips(){},updateNavigationButtons(){},renderNavigationDestination(){rendered++;context.navigationRenderGeneration++;},clearSelection(){state.selectedIds.clear();state.selectionAnchorId=null;},selectView(view,title){state.view=view;state.locationId=null;state.locationSubfolder='';state.selectedId=null;state.selectedIds.clear();state.filters.tags.clear();elements.title.textContent=title;context.renderNavigationDestination();},openPigeonTaggedView(){pigeon++;},refreshSimilarityGroups(){similarity++;}};
 vm.createContext(context);vm.runInContext(source.slice(source.indexOf('function captureNavigationSnapshot()'),source.indexOf('function applyNavigationSnapshot('))+source.slice(source.indexOf('let escapeAllTagsReturnState=null;'),source.indexOf('function thumbnailGridActive()')),context);
 return{context,state,elements,run:()=>vm.runInContext('runDoubleEscapeAction()',context),counts:()=>({quit,pigeon,rendered,similarity})};
}
test('Controls exposes all three double-Escape choices with unchanged Pigeon default',()=>{assert.match(source,/doubleEscapeAction:'pigeon'/);for(const [value,label] of [['pigeon','Virtual Pigeon Smart Folder'],['tags','All Tags'],['quit','Quit Pigeon immediately']])assert.match(html,new RegExp(`<option value="${value}">${label}`));assert.match(html,/<select id="double-escape-action" data-pref="doubleEscapeAction">/);assert.match(source,/if\(!\['pigeon','tags','quit'\]\.includes\(preferences\.doubleEscapeAction\)\)preferences\.doubleEscapeAction='pigeon'/);});
test('double Escape toggles All Tags back to exact originating folder, selection, filters and navigation',()=>{const h=harness();h.run();assert.equal(h.state.view,'tags');h.state.query='changed';h.state.filters.ratings.clear();h.run();assert.equal(h.state.view,'all');assert.equal(h.state.locationId,'folder');assert.equal(h.state.locationSubfolder,'photos');assert.equal(h.state.selectedId,'photo');assert.deepEqual([...h.state.selectedIds],['photo']);assert.deepEqual([...h.state.filters.tags],['travel']);assert.deepEqual([...h.state.filters.ratings],[5]);assert.equal(h.state.gridScrollTop,122);assert.equal(h.context.navigationReturnState.view,'favorites');assert.equal(h.context.navigationForwardState.view,'recent');assert.equal(h.elements.title.textContent,'Photos');assert.equal(h.counts().quit,0);});
test('returning to a scoped Duplicates comparison restarts the cancelled comparison',()=>{const h=harness();h.state.view='duplicates';h.state.duplicateSourceId='photo';h.run();h.run();assert.equal(h.state.view,'duplicates');assert.equal(h.state.duplicateSourceId,'photo');assert.equal(h.counts().similarity,1);});
test('Pigeon remains default; quit calls the dedicated app-exit bridge without navigating',()=>{const h=harness('pigeon');h.run();assert.equal(h.counts().pigeon,1);h.context.preferences.doubleEscapeAction='quit';h.run();assert.equal(h.counts().quit,1);assert.equal(h.counts().rendered,0);assert.equal(h.state.view,'all');assert.match(fs.readFileSync(path.join(__dirname,'../electron/preload.js'),'utf8'),/quitApp: \(\) => ipcRenderer.send\('app:quit'\)/);assert.match(fs.readFileSync(path.join(__dirname,'../electron/main.js'),'utf8'),/ipcMain.on\('app:quit', \(event\) => \{ if\(event.sender===mainWindow\?\.webContents\)app.quit\(\); \}\)/);});
test('All Tags does not return to a stale origin after another navigation or portfolio change',()=>{const h=harness();h.run();h.state.view='favorites';h.context.navigationRenderGeneration++;h.state.view='tags';h.run();assert.equal(h.state.view,'tags');assert.equal(vm.runInContext('escapeAllTagsReturnState.view',h.context),'tags');h.state.library.activePortfolioId='other';h.run();assert.equal(h.state.view,'tags');assert.equal(h.counts().quit,0);});
test('keyboard chord does not quit while closing editor, compare, map or contact sheet',()=>{assert.match(source,/lastEscapeShortcutAt=0;closeAnnotationEditor\(\);return;/);assert.match(source,/isImageCompareOpen\(\)\|\|!elements\.contactSheetView\.classList\.contains\('hidden'\)\|\|state\.mapOpen\)\)lastEscapeShortcutAt=0/);assert.match(source,/event\.defaultPrevented\|\|document\.querySelector\('dialog\[open\]'\)/);});
