const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),vm=require('node:vm');const text=require('node:fs').readFileSync(require.resolve('../electron/main.js'),'utf8'),code=text.slice(text.indexOf('async function duplicateAsset(id)'),text.indexOf('const EDITABLE_PREVIEW_EXTENSIONS'));
async function fixture(locations=[]){const root=await fs.mkdtemp(path.join(os.tmpdir(),'pigeon-duplicate-')),file=path.join(root,'original.png');await fs.writeFile(file,'original bytes');const source={id:'source',locationId:'removed-location',path:file,tags:['keep'],collectionIds:['collection'],rating:4},library={assets:[source],locations,collections:[{id:'collection',name:'Source collection',parentId:null}]},context={library,Date:class extends Date{constructor(...args){super(...(args.length?args:[2026,8,16,11,22,33]));}},libraryCore:require('../electron/library-core'),isCollectionLocked:()=>false,broadcastSidebar(){},fs:require('node:fs'),fsp:fs,path,isPermissionError:e=>['EACCES','EPERM'].includes(e.code),pathIsInside:(root,file)=>{const r=path.relative(root,file);return !r.startsWith('..')&&!path.isAbsolute(r);},isAssetLocked:a=>a.locked,watcherIgnoreUntil:new Map(),makeId:s=>s,isRemovable:async()=>false,watchLocation(){},inspectFile:async(p,l)=>({id:path.basename(p),path:p,locationId:l.id}),applyConfiguredCollectionTags(){},copyDuplicatePreview:async()=>false,mainAssetIndex:new Map(),scheduleAssetSave(){},scheduleMetadataSave(){},broadcastLocations(){},schedulePortfolioBackground(){},warmThumbnailCache(){},publicAssetForRenderer:a=>a};vm.createContext(context);vm.runInContext(code,context);return{root,file,source,context,library,run:()=>context.duplicateAsset('source'),close:()=>fs.rm(root,{recursive:true,force:true})};}
test('existing original can be duplicated after its location record was removed',async()=>{const h=await fixture();try{const result=await h.run();assert.equal(await fs.readFile(result.path,'utf8'),'original bytes');assert.equal(h.library.locations.length,0);assert.equal(result.locationId,h.source.locationId);assert.deepEqual([...result.tags],['keep']);assert.deepEqual([...result.collectionIds],['collection',h.library.collections.find(c=>c.name==='Duplicates').id]);assert.equal(path.basename(result.path),'original-16112233.png');assert.equal(result.rating,4);assert.equal(h.source.locationId,'removed-location');}finally{await h.close();}});
test('duplicate uses a covering folder and never overwrites a collision',async()=>{const h=await fixture();try{h.library.locations.push({id:'folder',type:'folder',path:h.root,assetCount:1});await fs.writeFile(path.join(h.root,'original-16112233.png'),'keep existing');const result=await h.run();assert.equal(result.locationId,'folder');assert.equal(path.basename(result.path),'original-16112233-2.png');assert.equal(await fs.readFile(path.join(h.root,'original-16112233.png'),'utf8'),'keep existing');}finally{await h.close();}});
test('missing originals report the actual path instead of blaming a location',async()=>{const h=await fixture();try{await fs.unlink(h.file);await assert.rejects(h.run(),/Original file unavailable.*original.png/);assert.equal(h.library.assets.length,1);}finally{await h.close();}});
test('simultaneous same-second copies use collision suffixes and one Duplicates collection',async()=>{const h=await fixture();try{const results=await Promise.all([h.run(),h.run()]);assert.equal(new Set(results.map(r=>r.path)).size,2);assert.equal(h.library.locations.length,0);assert.equal(h.library.collections.filter(c=>c.name==='Duplicates').length,1);assert.deepEqual(h.source.collectionIds,['collection']);for(const r of results){assert.equal(path.dirname(r.path),h.root);assert.equal(await fs.readFile(r.path,'utf8'),'original bytes');}}finally{await h.close();}});
test('single-file locations are reused, never replaced by new folder entries',async()=>{const h=await fixture();try{h.library.locations.push({id:h.source.locationId,type:'file',path:h.file});h.library.collections.push({id:'duplicates',name:'Duplicates',parentId:null});const result=await h.run();assert.equal(h.library.locations.length,1);assert.equal(result.locationId,h.source.locationId);assert.ok(result.collectionIds.includes('duplicates'));assert.equal(h.library.collections.length,2);}finally{await h.close();}});
test('locked Duplicates collection is not bypassed',async()=>{const h=await fixture();try{h.library.collections.push({id:'duplicates',name:'Duplicates'});h.context.isCollectionLocked=()=>true;await assert.rejects(h.run(),/Unlock the Duplicates/);assert.deepEqual(await fs.readdir(h.root),['original.png']);}finally{await h.close();}});
test('locked originals cannot bypass protection through duplication',async()=>{const h=await fixture();try{h.source.locked=true;await assert.rejects(h.run(),/Unlock/);}finally{await h.close();}});
