'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const renderer=fs.readFileSync(require('node:path').join(__dirname,'../src/renderer.js'),'utf8');
function harness(prepare,annotations=[]){const nodes=new Map(),node=key=>{if(!nodes.has(key)){const classes=new Set(key==='view'?['hidden']:[]);nodes.set(key,{style:{},classList:{add:x=>classes.add(x),remove:x=>classes.delete(x),contains:x=>classes.has(x),toggle:(x,value)=>value?classes.add(x):classes.delete(x)},setAttribute(){},querySelectorAll:()=>[]});}return nodes.get(key);};const asset={id:'image',name:'test',width:100,height:80,annotations},messages=[],state={library:{activePortfolioId:'test'},selectedId:asset.id,workingAnnotations:[],workingEdits:{}};const elements={annotationView:node('view'),annotationStage:node('stage'),grid:node('grid'),empty:node('empty'),tagBrowser:node('tags'),sentinel:node('sentinel'),status:node('status'),count:node('count')};const context={state,elements,assetById:()=>asset,isEditableVisualAsset:()=>true,showToast:message=>messages.push(message),hideContextMenu(){},hideDelegatedMagnifier(){},stopAllHoverPreviews(){},isInternalViewerOpen:()=>false,rendererAssetDerivatives:{upsert(){}},$:node,$$:()=>[],setTimeout,clearTimeout,crypto:require('node:crypto'),protectedUrl:()=>'',resetAiRemovalEditor(){},setAnnotationTool(){},requestAnimationFrame:fn=>fn(),previewEditRotation(){},applyAnnotationViewMode(){},renderGrid(){},renderInspector(){},window:{pigeon:{prepareImageEdit:()=>prepare?prepare(asset):Promise.resolve(asset),listPlugins:()=>new Promise(()=>{})},PigeonEditorRegionEffects:{clear(){}}}};vm.createContext(context);vm.runInContext(renderer.slice(renderer.indexOf('let annotationOpenSequence='),renderer.indexOf('function contactSheetAssets')),context);return{context,asset,messages,state,elements};}
test('editor opens without waiting for unrelated AI plugin inspection; proxy layers are copied',async()=>{const h=harness(null,new Proxy([{id:'layer',type:'rect',x:1,y:1,width:10,height:10}],{}));await h.context.openAnnotationEditor('image');assert.equal(h.elements.annotationView.classList.contains('hidden'),false);assert.equal(h.elements.annotationView.classList.contains('editor-preparing'),false);assert.equal(h.state.workingAnnotations.length,1);assert.deepEqual(h.messages,[]);});
test('pending editor preparation is visible and closing prevents late reopening',async()=>{let resolve;const h=harness(()=>new Promise(r=>resolve=r)),pending=h.context.openAnnotationEditor('image');assert.equal(h.elements.annotationView.classList.contains('hidden'),false);assert.equal(h.elements.annotationView.classList.contains('editor-preparing'),true);h.context.closeAnnotationEditor();resolve(h.asset);await pending;assert.equal(h.elements.annotationView.classList.contains('hidden'),true);assert.equal(h.state.annotationAssetId,null);});
test('preparation failures are reported and the grid is restored',async()=>{const h=harness(async()=>{throw Error('Permission denied');});await h.context.openAnnotationEditor('image');assert.equal(h.elements.annotationView.classList.contains('hidden'),true);assert.match(h.messages[0],/Could not open image editor: Permission denied/);});
test('legacy serialized layer arrays are supported',async()=>{const h=harness(null,JSON.stringify([{id:'layer',type:'text',text:'hello'}]));await h.context.openAnnotationEditor('image');assert.equal(h.state.workingAnnotations[0].text,'hello');assert.deepEqual(h.messages,[]);});
test('imported layer identifiers and colors cannot inject editor markup or styles',async()=>{const h=harness(null,JSON.stringify([{id:'" onpointerdown="bad',type:'rect',color:'#fff; background:red'}]));await h.context.openAnnotationEditor('image');assert.match(h.state.workingAnnotations[0].id,/^[a-z0-9_-]+$/i);assert.equal(h.state.workingAnnotations[0].color,'#ff3b30');assert.deepEqual(h.messages,[]);});
test('initialization errors cannot leave an invisible unhandled editor failure',async()=>{const h=harness();h.context.setAnnotationTool=()=>{throw Error('Control unavailable');};await h.context.openAnnotationEditor('image');assert.equal(h.elements.annotationView.classList.contains('hidden'),true);assert.match(h.messages[0],/Control unavailable/);});
