const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require.resolve('../src/renderer.js'),'utf8'),body=source.slice(source.indexOf('async function requestAiRemovalPreview('),source.indexOf("$('#run-ai-removal').addEventListener"));
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve};};
function harness(overrides={}){const nodes=new Map(),calls=[];const context={annotationOpenSequence:1,aiRemovalBusy:false,state:{aiMaskPainted:true,aiRemovalToken:null},$:id=>{if(!nodes.has(id))nodes.set(id,{dataset:{},classList:{add(){},remove(){}},toDataURL:()=> 'data:image/png;base64,mask'});return nodes.get(id);},editorAssetId:()=> 'asset',assetById:()=>({id:'asset'}),showToast(){},updateAiRemovalProgress(){},requestAnimationFrame:setImmediate,setInterval,clearInterval,refreshAiRemovalEditorStatus:async()=>{},setAiRemovalProgress:active=>{context.aiRemovalBusy=active;calls.push(['progress',active]);},window:{pigeon:{listPlugins:async()=>[{id:'ai-removal',installed:false,modelReady:false}],preparePlugin:async()=>{calls.push(['prepare']);return[{id:'ai-removal',enabled:false}];},setPluginEnabled:async()=>calls.push(['enable']),previewAiRemoval:async()=>{calls.push(['preview']);return{token:'result',previewUrl:'preview'};},discardAiRemoval:async token=>calls.push(['discard',token]),...overrides}}};vm.createContext(context);vm.runInContext(body,context);return{context,calls,nodes,run:operation=>context.requestAiRemovalPreview(operation)};}
test('first removal click prepares missing runtime/model automatically and then performs removal',async()=>{const h=harness();await h.run();assert.deepEqual(h.calls.filter(c=>c[0]!=='progress').map(c=>c[0]),['prepare','enable','preview']);assert.equal(h.context.state.aiRemovalToken,'result');assert.equal(h.context.aiRemovalBusy,false);});
test('closing or replacing the editor during setup cannot enable or publish into another session',async()=>{const waiting=deferred(),started=deferred();const h=harness({preparePlugin:()=>{started.resolve();return waiting.promise;}}),operation=h.run();await started.promise;h.context.annotationOpenSequence++;h.context.aiRemovalBusy=true;waiting.resolve([{id:'ai-removal',enabled:false}]);await operation;assert.ok(!h.calls.some(c=>['preview','enable'].includes(c[0])));assert.equal(h.context.aiRemovalBusy,true);});
test('late inference output is discarded without overwriting a newer editor preview',async()=>{const waiting=deferred(),started=deferred();const h=harness({listPlugins:async()=>[{id:'ai-removal',installed:true,modelReady:true,enabled:true}],previewAiRemoval:()=>{started.resolve();return waiting.promise;}}),operation=h.run();await started.promise;h.context.annotationOpenSequence++;h.context.state.aiRemovalToken='newer';waiting.resolve({token:'late',previewUrl:'late-preview'});await operation;assert.equal(h.context.state.aiRemovalToken,'newer');assert.ok(h.calls.some(c=>c[0]==='discard'&&c[1]==='late'));});
test('rapid repeat clicks start only one setup/inference operation',async()=>{const h=harness();await Promise.all([h.run(),h.run()]);assert.equal(h.calls.filter(c=>c[0]==='prepare').length,1);assert.equal(h.calls.filter(c=>c[0]==='preview').length,1);});
test('background removal requires no painted mask and passes its operation through IPC',async()=>{let received;const h=harness({previewAiRemoval:async(...args)=>{received=args;return{token:'bg',previewUrl:'data:image/png;base64,png'};}});h.context.state.aiMaskPainted=false;await h.run('background');assert.equal(received[3],'background');assert.equal(h.context.state.aiRemovalOperation,'background');assert.equal(h.context.state.aiRemovalToken,'bg');});
test('modal Escape and editor pointer interaction cannot trigger gallery actions',()=>{assert.match(source,/event\.key==='Escape'&&\(event\.defaultPrevented\|\|document\.querySelector\('dialog\[open\]'\)\)/);assert.match(source,/gridWrap\.addEventListener\('pointerdown',\(event\)=>\{if\(!thumbnailGridActive\(\)/);assert.match(source,/gridWrap\.addEventListener\('wheel', \(event\) => \{\s*if\(!thumbnailGridActive\(\)\)return/);});
test('loopback removal rejects browser origins and non-JSON requests before accessing paths',()=>{const python=fs.readFileSync(require.resolve('../electron/plugin-examples/ai-removal/server.py'),'utf8'),handler=python.slice(python.indexOf('def inpaint():'));assert.ok(handler.indexOf('request.headers.get("Origin")')<handler.indexOf('source = Path'));assert.match(handler,/Browser requests are not allowed.*403/);assert.match(handler,/JSON requests are required.*415/);});
