const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{DatabaseSync}=require('node:sqlite');
const {collect,cosine,normalized,cluster}=require('../electron/knowledge-graph-worker');
const {createKnowledgeGraph}=require('../electron/knowledge-graph');
const {fingerprint,fingerprintsMatch}=require('../electron/semantic-policy');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'pigeon-graph-')),databaseFile=path.join(root,'library.db'),assets=Array.from({length:12},(_,i)=>({id:'a'+i,fingerprint:'fp'+i,name:'File '+i,kind:i<6?'image':'document',tags:[i<6?'birds':'cats']})),db=new DatabaseSync(databaseFile+'.semantic.sqlite3');t.after(()=>fs.rmSync(root,{recursive:true,force:true}));db.exec('CREATE TABLE assets(id TEXT PRIMARY KEY,fingerprint TEXT,version TEXT,complete INTEGER,metadata_dirty INTEGER);CREATE TABLE vectors(asset_id TEXT,part INTEGER,vector BLOB,PRIMARY KEY(asset_id,part))');for(const[i,asset]of assets.entries()){db.prepare('INSERT INTO assets VALUES(?,?,?,?,?)').run(asset.id,asset.fingerprint,'embeddinggemma2-768-f32-v1',1,0);const values=new Float32Array(768);values[i<6?0:1]=1;for(const part of [0,1])db.prepare('INSERT INTO vectors VALUES(?,?,?)').run(asset.id,part,Buffer.from(values.buffer));}db.close();return{portfolioId:'one',databaseFile,assets,mode:'overview',minimum:.5,limit:600,groupBy:'semantic'};}
test('portfolio overview clusters actual stored vectors into colored hubs and deterministic file spokes',t=>{const input=fixture(t),result=collect(input),again=collect(input);assert.equal(result.files,12);assert.equal(result.groups.length,2);assert.equal(result.nodes.filter(node=>node.group).length,2);assert.equal(result.edges.filter(edge=>edge.membership).length,12);assert.deepEqual(result.nodes,again.nodes);assert.match(result.method,/Cosine/);assert.ok(result.nodes.every(node=>Number.isFinite(node.position.x)&&Number.isFinite(node.position.y)));assert.equal(result.indexed,12);});
test('file neighborhoods use cosine connections across the full allowed portfolio rather than shared filenames or tags',t=>{const input=fixture(t),result=collect({...input,mode:'focus',rootId:'a0'});assert.equal(result.rootId,'a0');assert.equal(result.files,6);assert.ok(result.nodes.filter(node=>node.assetId!=='a0').every(node=>node.kind==='image'));assert.ok(result.edges.every(edge=>edge.score>.99));assert.equal(result.truncated,false);});
test('stale, incomplete, metadata-dirty, wrong-version and unauthorized files are excluded from graph responses',t=>{const input=fixture(t),db=new DatabaseSync(input.databaseFile+'.semantic.sqlite3');db.exec("UPDATE assets SET fingerprint='old' WHERE id='a0';UPDATE assets SET complete=0 WHERE id='a1';UPDATE assets SET metadata_dirty=1 WHERE id='a2';UPDATE assets SET version='other' WHERE id='a3'");db.close();input.assets=input.assets.filter(asset=>asset.id!=='a4');const result=collect(input);assert.equal(result.files,7);assert.ok(result.nodes.every(node=>!['a0','a1','a2','a3','a4'].includes(node.assetId)));assert.equal(collect({...input,mode:'focus',rootId:'a4'}).nodes.length,0);});
test('bounded overviews report sampling and support actual file-type and tag grouping',t=>{const input=fixture(t),sample=collect({...input,limit:10});assert.equal(sample.files,10);assert.equal(sample.sampled,true);assert.deepEqual(collect({...input,groupBy:'kind'}).groups.map(group=>group.name).sort(),['document','image']);assert.deepEqual(collect({...input,groupBy:'tags'}).groups.map(group=>group.name).sort(),['birds','cats']);});
test('graph requests do not create missing semantic databases or start a model',t=>{const input=fixture(t),missing=path.join(path.dirname(input.databaseFile),'missing.db'),result=collect({...input,databaseFile:missing});assert.equal(result.nodes.length,0);assert.match(result.message,/Analyze/);assert.equal(fs.existsSync(missing+'.semantic.sqlite3'),false);});
test('worker responses are cancelled rather than mixed when the active portfolio changes',async t=>{let input=fixture(t);const service=createKnowledgeGraph({getContext:()=>input});t.after(()=>service.close());const request=service.get({portfolioId:'one'});input={...input,portfolioId:'two',databaseFile:input.databaseFile+'-two'};await assert.rejects(request,/Portfolio changed/);});
test('post-computation validation rejects changed or newly locked assets',async t=>{const input=fixture(t),service=createKnowledgeGraph({getContext:()=>input,validateResult:()=>false});t.after(()=>service.close());const result=await service.get();assert.deepEqual(result.nodes,[]);assert.match(result.message,/changed/);});
test('legacy portfolio fingerprints remain valid without re-indexing unchanged media, but edits and tag changes do not match',()=>{const asset={path:'/image.jpg',size:12,modified:1,name:'Image',tags:['bird']},legacy=JSON.stringify([asset.path,asset.size,asset.modified,'',asset.name,'',asset.tags,'','']);assert.equal(fingerprintsMatch(fingerprint(asset),legacy),true);assert.equal(fingerprintsMatch(fingerprint({...asset,tags:['cat']}),legacy),false);assert.equal(fingerprintsMatch(fingerprint({...asset,editedPath:'/edited.png',editedAt:2}),legacy),false);assert.equal(fingerprintsMatch(fingerprint(asset),'invalid'),false);});
test('zero and orthogonal vectors are handled safely, and semantic clustering is deterministic',()=>{assert.equal(normalized([0,0]),null);assert.equal(cosine(normalized([1,0]),normalized([0,1])),0);const points=[{v:normalized([1,0])},{v:normalized([1,.1])},{v:normalized([0,1])}];assert.deepEqual(cluster(points).assignments,cluster(points).assignments);});
