'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const os=require('node:os');
const path=require('node:path');
const fs=require('node:fs');
const fsp=require('node:fs/promises');
const crypto=require('node:crypto');
const yazl=require('yazl');
const {createCollection,inspectCollection,extractCollectionFiles,validateManifest,PIGEON_COLLECTION_MIME}=require('../electron/pigeon-collection');

async function temporaryDirectory(){return fsp.mkdtemp(path.join(os.tmpdir(),'pigeon-collection-test-'));}
function writeZip(target,entries){return new Promise((resolve,reject)=>{const zip=new yazl.ZipFile(),output=fs.createWriteStream(target);for(const[name,body]of entries)zip.addBuffer(Buffer.from(body),name);zip.outputStream.once('error',reject);output.once('error',reject);output.once('close',resolve);zip.outputStream.pipe(output);zip.end();});}
function manifestFor(name,body,{version=1,hash=null}={}){return{format:'pigeon-collection',formatVersion:version,name:'Test',id:crypto.randomUUID(),createdAt:new Date().toISOString(),createdBy:{application:'Pigeon',version:'test'},files:[{id:crypto.randomUUID(),path:name,originalName:path.basename(name),mimeType:'application/octet-stream',size:body.length,sha256:hash||crypto.createHash('sha256').update(body).digest('hex'),relativePath:''}]};}

test('creates, inspects, and selectively extracts a portable Pigeon Collection',async(t)=>{const directory=await temporaryDirectory();t.after(()=>fsp.rm(directory,{recursive:true,force:true}));const sourceA=path.join(directory,'hello world.txt'),sourceB=path.join(directory,'猫.bin'),target=path.join(directory,'Family Holiday.pigeon');await fsp.writeFile(sourceA,'hello');await fsp.writeFile(sourceB,Buffer.from([0,1,2,3]));const created=await createCollection({name:'Family Holiday',destination:target,applicationVersion:'1.2.3',files:[{sourcePath:sourceA,relativePath:'Notes'},{sourcePath:sourceB,relativePath:'資料'}]});assert.equal(created.files,2);const opened=await inspectCollection(target);assert.equal(opened.mimeType,PIGEON_COLLECTION_MIME);assert.equal(opened.validFiles,2);assert.equal(opened.invalidFiles,0);assert.deepEqual(opened.files.map((file)=>file.relativePath),['Notes','資料']);const extraction=path.join(directory,'extract'),outputs=await extractCollectionFiles(target,[opened.files[1].id],extraction);assert.equal(outputs.length,1);assert.equal(await fsp.readFile(outputs[0].path,'hex'),'00010203');});

test('rejects empty exports and unsupported future manifests',async()=>{await assert.rejects(createCollection({name:'Empty',destination:'/tmp/empty.pigeon',files:[]}),/Select at least one/);const manifest=manifestFor('files/id/a.txt',Buffer.from('a'),{version:2});assert.throws(()=>validateManifest(manifest),/newer version/);});

test('reports a corrupt payload without hiding valid files',async(t)=>{const directory=await temporaryDirectory();t.after(()=>fsp.rm(directory,{recursive:true,force:true}));const target=path.join(directory,'corrupt.pigeon'),good=Buffer.from('good'),bad=Buffer.from('tampered'),goodManifest=manifestFor('files/good/good.txt',good),badRecord=manifestFor('files/bad/bad.txt',Buffer.from('expected')).files[0],manifest={...goodManifest,files:[goodManifest.files[0],badRecord]};await writeZip(target,[['files/good/good.txt',good],['files/bad/bad.txt',bad],['manifest.json',JSON.stringify(manifest)]]);const opened=await inspectCollection(target);assert.equal(opened.validFiles,1);assert.equal(opened.invalidFiles,1);assert.equal(opened.files.find((file)=>file.status==='corrupt').error.length>0,true);});

test('rejects missing manifests, duplicate paths, and archive traversal',async(t)=>{const directory=await temporaryDirectory();t.after(()=>fsp.rm(directory,{recursive:true,force:true}));const missing=path.join(directory,'missing.pigeon');await writeZip(missing,[['file.txt','x']]);await assert.rejects(inspectCollection(missing),/manifest.json is missing/);const duplicate=path.join(directory,'duplicate.pigeon'),body=Buffer.from('x'),manifest=manifestFor('files/id/x.txt',body);await writeZip(duplicate,[['files/id/x.txt',body],['FILES/ID/X.TXT',body],['manifest.json',JSON.stringify(manifest)]]);await assert.rejects(inspectCollection(duplicate),/Duplicate archive path/);const safe=path.join(directory,'safe.pigeon');await writeZip(safe,[['aa/outside.txt','x'],['manifest.json',JSON.stringify(manifest)]]);let bytes=await fsp.readFile(safe);bytes=Buffer.from(bytes.toString('binary').replaceAll('aa/outside.txt','../outside.txt'),'binary');const malicious=path.join(directory,'malicious.pigeon');await fsp.writeFile(malicious,bytes);await assert.rejects(inspectCollection(malicious),/Unsafe Pigeon Collection path|invalid relative path/);});

test('enforces declared uncompressed and compression-ratio limits',async(t)=>{const directory=await temporaryDirectory();t.after(()=>fsp.rm(directory,{recursive:true,force:true}));const target=path.join(directory,'bomb.pigeon'),body=Buffer.alloc(100000,0),manifest=manifestFor('files/id/zeros.bin',body);await writeZip(target,[['files/id/zeros.bin',body],['manifest.json',JSON.stringify(manifest)]]);await assert.rejects(inspectCollection(target,{limits:{maxCompressionRatio:2}}),/compression-ratio limit/);});
