const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const{resolvePluginPython}=require('../electron/plugin-python');
const{createPluginManager}=require('../electron/plugin-manager');
const missing=()=>{throw Error('not found');};
test('automatic setup installs missing managed Python with uv, without replacing system Python',async()=>{let installed=false;const calls=[];const run=async(command,args)=>{calls.push([command,args]);if(command==='uv'&&args[0]==='--version')return'uv';if(command==='uv'&&args[0]==='python'&&args[1]==='install'){installed=true;return'ok';}if(command==='uv'&&args[1]==='find'&&installed)return'/private/python3.11';if(command==='/private/python3.11')return'/private/python3.11\n3.11';return missing();};assert.deepEqual(await resolvePluginPython('auto',{run,installMissing:true}),{executable:'/private/python3.11',version:'3.11'});assert.equal(calls.filter(c=>c[1][1]==='install').length,1);assert.ok(!calls.flat(2).includes('--default'));});
test('discovery never downloads and explicit incompatible interpreters are not silently replaced',async()=>{const calls=[];const run=async(command,args)=>{calls.push(args);if(args[0]==='--version')return'uv';if(args[0]==='-c')return'/python\n3.13';return missing();};await assert.rejects(resolvePluginPython('auto',{run}),/automatic setup/);assert.ok(!calls.some(a=>a.includes('install')));calls.length=0;await assert.rejects(resolvePluginPython('/custom/python',{run,installMissing:true}),/compatible executable/);assert.equal(calls.length,1);});
test('canceled runtime discovery cannot fall through to installation',async()=>{const controller=new AbortController();let calls=0;await assert.rejects(resolvePluginPython('auto',{installMissing:true,signal:controller.signal,run:async()=>{calls++;controller.abort();throw Error('missing');}}),/abort/i);assert.equal(calls,1);});
test('missing uv can be bootstrapped into private storage, with isolated module lookup',async()=>{const directory=await fs.mkdtemp(path.join(os.tmpdir(),'pigeon-runtime-test-'));let pip=false,installed=false;const calls=[];try{const run=async(command,args)=>{calls.push(args);if(args.includes('pip')){assert.ok(args.includes('--target'));assert.ok(args.includes(directory));assert.ok(args.includes('--only-binary=:all:'));pip=true;return'ok';}if(pip&&args.includes('runpy.run_module("uv",run_name="__main__")'))throw Error('unexpected');if(pip&&args.includes(directory)){assert.ok(args.includes('-I'));if(args.at(-1)==='--version')return'uv';if(args.includes('install')){installed=true;return'ok';}if(installed&&args.includes('find'))return'/managed/python';}if(command==='/managed/python')return'/managed/python\n3.11';return missing();};assert.equal((await resolvePluginPython('auto',{run,installMissing:true,managedDir:directory})).version,'3.11');assert.ok(pip&&installed);}finally{await fs.rm(directory,{recursive:true,force:true});}});
test('enlarger is cataloged as a bundled tool and verifies actual inference without Python',async()=>{const directory=await fs.mkdtemp(path.join(os.tmpdir(),'pigeon-bundled-test-')),manager=createPluginManager({pluginsDir:directory,bundledDir:path.join(__dirname,'../electron/plugin-examples')});try{const item=(await manager.list()).find(p=>p.id==='ai-enlarger');assert.equal(item.bundled,true);assert.equal(item.installed,true);assert.equal(item.modelReady,true);assert.equal((await manager.health(item.id)).ok,true);assert.match((await manager.list()).find(p=>p.id===item.id).statusDetail,/real ONNX inference/);await assert.rejects(manager.uninstall(item.id),/not found/);manager.close();assert.equal((await manager.health(item.id)).ok,false);}finally{manager.close();await fs.rm(directory,{recursive:true,force:true});}});
