const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),syncFs=require('node:fs'),os=require('node:os'),path=require('node:path'),vm=require('node:vm'),{EventEmitter}=require('node:events'),{createRequire}=require('node:module');
const filename=require.resolve('../electron/plugin-manager'),realRequire=createRequire(filename),source=syncFs.readFileSync(filename,'utf8');
async function harness({fetch:fetcher=async()=>{throw Error('Unexpected network request');},badRuntime=false,badDependencies=false,onProbe=null,validationFailures=0}={}){const root=await fs.mkdtemp(path.join(os.tmpdir(),'pigeon-setup-test-')),directory=path.join(root,'ai-removal'),venv=path.join(directory,'.venv'),python=path.join(venv,process.platform==='win32'?'Scripts/python.exe':'bin/python'),calls=[];let dependenciesHealthy=!badDependencies;
 const spawn=(command,args)=>{const child=new EventEmitter();child.stdout=new EventEmitter();child.stderr=new EventEmitter();child.unref=()=>{};child.kill=()=>{child.killed=true;child.emit('close',1);child.emit('exit',1);};calls.push({command,args});setImmediate(async()=>{try{let output='';if(args.includes('python')&&args.includes('find'))output='/managed/python3.11';else if(args.includes('--version'))output='available';else if(args.includes('-c')&&args.at(-1).includes('sys.version_info'))output=`${command}\n${command===python&&await fs.readFile(python,'utf8')==='bad'?'3.13':'3.11'}`;else if(args.includes('venv')){await fs.mkdir(path.dirname(python),{recursive:true});await fs.writeFile(python,'good');}else if(args.includes('--force-reinstall'))dependenciesHealthy=true;else if(args.includes('-c')&&args.at(-1).includes('import flask')){if(onProbe)await onProbe();if(!dependenciesHealthy)throw Error('missing module');}else if(args.includes('--prepare-model')){if(validationFailures-->0)throw Error('corrupt model');await fs.writeFile(path.join(directory,'.model-ready'),'ready');}else if(args.includes(path.join(directory,'server.py')))return;if(child.killed)return;child.stdout.emit('data',Buffer.from(output));child.emit('exit',0);}catch(error){child.stderr.emit('data',Buffer.from(error.message));child.emit('exit',1);}});return child;};
 const context={module:{exports:{}},require:id=>id==='node:child_process'?{spawn}:realRequire(id),__dirname:path.dirname(filename),Buffer,process,console,URL,AbortController,AbortSignal,setTimeout,clearTimeout,fetch:fetcher};vm.runInNewContext(source,context,{filename});const manager=context.module.exports.createPluginManager({pluginsDir:root,bundledDir:path.join(__dirname,'../electron/plugin-examples')});await manager.install('ai-removal');await fs.mkdir(path.dirname(python),{recursive:true});await fs.writeFile(python,badRuntime?'bad':'good');await fs.mkdir(path.join(directory,'models'),{recursive:true});const target=path.join(directory,'models/lama_fp32.onnx'),partial=target+'.partial';return{manager,directory,python,target,partial,calls,async modelReady(){await fs.writeFile(target,'');await fs.truncate(target,208044816);await fs.writeFile(path.join(directory,'.model-ready'),'ready');},async close(){manager.close();await fs.rm(root,{recursive:true,force:true});}};}
test('HTTP errors preserve the partial model for a later retry',async()=>{const h=await harness({fetch:async()=>new Response('Unavailable',{status:503})});try{await fs.writeFile(h.partial,'previous bytes');await assert.rejects(h.manager.setup('ai-removal'),/HTTP 503/);assert.equal(await fs.readFile(h.partial,'utf8'),'previous bytes');}finally{await h.close();}});
test('incorrect resume ranges are rejected before altering cached bytes',async()=>{const h=await harness({fetch:async()=>new Response('bad',{status:206,headers:{'content-range':'bytes 0-208044815/208044816'}})});try{await fs.writeFile(h.partial,'previous bytes');await assert.rejects(h.manager.setup('ai-removal'),/invalid byte range/);assert.equal(await fs.readFile(h.partial,'utf8'),'previous bytes');}finally{await h.close();}});
test('a truncated model above the minimum size is retained as partial, never published as complete',async()=>{const prefix=150*1024*1024,h=await harness({fetch:async()=>new Response('tail',{status:206,headers:{'content-range':`bytes ${prefix}-208044815/208044816`}})});try{await fs.writeFile(h.partial,'');await fs.truncate(h.partial,prefix);await assert.rejects(h.manager.setup('ai-removal'),/incomplete/);assert.equal((await fs.stat(h.partial)).size,prefix+4);await assert.rejects(fs.stat(h.target),/ENOENT/);}finally{await h.close();}});
test('incompatible private environments are backed up and recreated rather than reused',async()=>{const h=await harness({badRuntime:true});try{await h.modelReady();await h.manager.setup('ai-removal');assert.equal(await fs.readFile(h.python,'utf8'),'good');assert.ok((await fs.readdir(h.directory)).some(p=>p.startsWith('.venv.repair-')));assert.ok(h.calls.some(c=>c.args.includes('venv')));}finally{await h.close();}});
test('interrupted dependency installations are force-repaired before model validation',async()=>{const h=await harness({badDependencies:true});try{await h.modelReady();await h.manager.setup('ai-removal');assert.ok(h.calls.some(c=>c.args.includes('--force-reinstall')));assert.equal((await h.manager.list()).find(p=>p.id==='ai-removal').status,'ready');}finally{await h.close();}});
test('model validation failures back up the corrupt cache and download a replacement',async()=>{const prefix=208044800,h=await harness({validationFailures:1,fetch:async()=>new Response(Buffer.alloc(16),{status:206,headers:{'content-range':`bytes ${prefix}-208044815/208044816`}})});try{await h.modelReady();await fs.writeFile(h.partial,'');await fs.truncate(h.partial,prefix);await h.manager.setup('ai-removal');assert.equal((await fs.stat(h.target+'.invalid')).size,208044816);assert.equal((await h.manager.list()).find(p=>p.id==='ai-removal').modelReady,true);assert.equal(h.calls.filter(c=>c.args.includes('--prepare-model')).length,2);}finally{await h.close();}});
test('a runtime probe finishing after close cannot launch a service',async()=>{let release,started;const gate=new Promise(r=>release=r),ready=new Promise(r=>started=r),h=await harness({onProbe:()=>{started();return gate;}});try{await h.modelReady();const operation=h.manager.setEnabled('ai-removal',true);await ready;h.manager.close();release();await assert.rejects(operation,/closed/);assert.equal(h.calls.filter(c=>c.args.includes(path.join(h.directory,'server.py'))).length,0);}finally{await h.close();}});
test('concurrent enable requests share one local service start',async()=>{const h=await harness({fetch:async()=>new Response(JSON.stringify({ok:true,modelReady:true,model:'test model'}))});try{await h.modelReady();await Promise.all([h.manager.setEnabled('ai-removal',true),h.manager.setEnabled('ai-removal',true)]);assert.equal(h.calls.filter(c=>c.args.includes(path.join(h.directory,'server.py'))&&!c.args.includes('--prepare-model')).length,1);}finally{await h.close();}});
