const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{Worker}=require('node:worker_threads'),{DatabaseSync}=require('node:sqlite');
const {writeSemanticMetadata}=require('../electron/semantic-metadata');
const {createLibraryStore}=require('../electron/database');
const core=require('../electron/library-core');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'pigeon-paused-meta-')),file=path.join(root,'library.db.semantic.sqlite3'),db=new DatabaseSync(file);t.after(()=>fs.rmSync(root,{recursive:true,force:true}));db.exec("CREATE TABLE assets(id TEXT PRIMARY KEY,fingerprint TEXT,metadata TEXT,metadata_dirty INTEGER,cursor INTEGER,complete INTEGER);CREATE TABLE vectors(asset_id TEXT,part INTEGER,vector BLOB);INSERT INTO assets VALUES('a','old','{}',0,3,0)");db.prepare('INSERT INTO vectors VALUES(?,?,?)').run('a',1,Buffer.from('unchanged image vector'));db.close();return{root,file};}
test('independent metadata writes remain available during an in-flight paused scan without touching its vectors or checkpoint',t=>{const{file}=fixture(t),record={asset:{id:'a',path:'/source.jpg',tags:['new tag'],imagePath:'/edited.png'},fingerprint:'new'};assert.equal(writeSemanticMetadata(file,[record]).updated,1);const db=new DatabaseSync(file),row=db.prepare('SELECT * FROM assets').get();assert.deepEqual(JSON.parse(row.metadata).tags,['new tag']);assert.equal(JSON.parse(row.metadata).imagePath,'/edited.png');assert.equal(row.fingerprint,'old','engine synchronization owns fingerprint invalidation');assert.equal(row.cursor,3);assert.equal(row.complete,0);assert.equal(row.metadata_dirty,1);assert.equal(Buffer.from(db.prepare('SELECT vector FROM vectors').get().vector).toString(),'unchanged image vector');db.close();assert.equal(writeSemanticMetadata(file,[record]).updated,0,'repeated queued changes do not rewrite identical metadata');});
test('the ordinary asset-save worker writes semantic metadata alongside saved tags, independently of Python activity',async t=>{const{root,file}=fixture(t),databaseFile=path.join(root,'library.db'),asset={id:'a',path:'/source.jpg',kind:'image',name:'a',tags:['saved tag'],size:1,modified:1};const store=createLibraryStore(databaseFile);store.save(core.migrateLibrary({assets:[asset],locations:[]}));store.close();const worker=new Worker(path.resolve('electron/database-worker.js'),{workerData:{databaseFile}});t.after(()=>worker.terminate());const response=new Promise((resolve,reject)=>{worker.once('message',resolve);worker.once('error',reject);});worker.postMessage({id:1,action:'upsert-assets',library:{assets:[asset]},target:{semanticRecords:[{asset,fingerprint:'new'}]}});const result=await response;assert.equal(result.ok,true);assert.equal(result.metrics.semanticRecords,1);const db=new DatabaseSync(file);assert.deepEqual(JSON.parse(db.prepare('SELECT metadata FROM assets').get().metadata).tags,['saved tag']);db.close();await worker.terminate();});
test('missing and legacy databases defer to engine migration without creating or changing their schemas',t=>{const{root}=fixture(t),missing=path.join(root,'missing.sqlite3');assert.equal(writeSemanticMetadata(missing,[{asset:{id:'a'},fingerprint:'new'}]).updated,0);assert.equal(fs.existsSync(missing),false);const legacy=path.join(root,'legacy.sqlite3'),db=new DatabaseSync(legacy);db.exec('CREATE TABLE assets(id TEXT,fingerprint TEXT)');db.close();assert.equal(writeSemanticMetadata(legacy,[{asset:{id:'a'},fingerprint:'new'}]).deferred,true);const reopened=new DatabaseSync(legacy);assert.deepEqual(reopened.prepare('PRAGMA table_info(assets)').all().map(row=>row.name),['id','fingerprint']);reopened.close();});
test('a busy semantic transaction safely defers the sidecar write rather than failing the source-library save',t=>{const{file}=fixture(t),lock=new DatabaseSync(file);lock.exec('BEGIN IMMEDIATE');const result=writeSemanticMetadata(file,[{asset:{id:'a',tags:['new']},fingerprint:'new'}]);assert.equal(result.updated,0);assert.match(result.error,/locked|busy/i);lock.exec('ROLLBACK');lock.close();});
