const fsp=require('node:fs/promises');
const path=require('node:path');
const {spawn}=require('node:child_process');

const BUILT_IN_PLUGINS=[{id:'ai-removal',name:'AI Object Removal',version:'1.0.0',author:'Pigeon',category:'Image editing',description:'Remove painted objects with a private Simple LaMa vision-inpainting model running on this computer.',kind:'service',entry:'server.py',model:{name:'Simple LaMa ONNX',type:'Vision inpainting',size:'Approximately 200 MB',purpose:'Object removal and background reconstruction'},configSchema:[{key:'endpoint',label:'Local endpoint',type:'url',default:'http://127.0.0.1:8765/inpaint'},{key:'pythonExecutable',label:'Python 3.10/3.11 executable',type:'text',default:'auto'},{key:'brushSize',label:'Default mask brush size',type:'number',min:5,max:200,default:45}]}];
const defaultState=()=>({plugins:{}});
function safeState(value){return value&&typeof value==='object'&&value.plugins&&typeof value.plugins==='object'?value:defaultState();}
function pluginDefaults(plugin){return Object.fromEntries((plugin.configSchema||[]).map((field)=>[field.key,field.default]));}
function isLoopbackEndpoint(value){try{const url=new URL(String(value));return url.protocol==='http:'&&['127.0.0.1','localhost','::1','[::1]'].includes(url.hostname);}catch{return false;}}
function runCommand(command,args,cwd,timeoutMs=600000){return new Promise((resolve,reject)=>{const child=spawn(command,args,{cwd,windowsHide:true,stdio:['ignore','pipe','pipe']}),output=[];let settled=false;const timer=setTimeout(()=>{child.kill();reject(new Error('Plugin setup timed out'));},timeoutMs);child.stdout.on('data',(chunk)=>output.push(String(chunk)));child.stderr.on('data',(chunk)=>output.push(String(chunk)));child.once('error',(error)=>{if(settled)return;settled=true;clearTimeout(timer);reject(error);});child.once('exit',(code)=>{if(settled)return;settled=true;clearTimeout(timer);code===0?resolve(output.join('').slice(-4000)):reject(new Error(output.join('').slice(-800)||`Plugin setup exited with code ${code}`));});});}
async function compatiblePython(configured='auto'){const requested=String(configured||'auto').trim(),check=async(executable,args=[])=>{try{const output=await runCommand(executable,[...args,'-c','import sys; print(sys.executable); print(f"{sys.version_info.major}.{sys.version_info.minor}")'],process.cwd(),20000),lines=output.trim().split(/\r?\n/),version=lines.at(-1);return['3.10','3.11'].includes(version)?lines.at(-2):null;}catch{return null;}};if(!['auto','python'].includes(requested.toLowerCase())){const found=await check(requested);if(found)return found;throw new Error('AI Object Removal requires Python 3.10 or 3.11. Update the configured Python executable.');}if(process.platform==='win32'){const launcher=await check('py',['-3.11']);if(launcher)return launcher;}try{const found=(await runCommand('uv',['python','find','3.11'],process.cwd(),20000)).trim().split(/\r?\n/).at(-1);if(found&&await check(found))return found;}catch{}const system=await check('python');if(system)return system;throw new Error('Python 3.10 or 3.11 was not found. Install Python 3.11 or configure its executable in Plugin Manager.');}
function createPluginManager({pluginsDir,bundledDir}){
  const stateFile=path.join(pluginsDir,'plugin-state.json'),processes=new Map(),runtime=new Map();
  async function load(){try{return safeState(JSON.parse(await fsp.readFile(stateFile,'utf8')));}catch{return defaultState();}}
  async function save(state){await fsp.mkdir(pluginsDir,{recursive:true});await fsp.writeFile(stateFile,JSON.stringify(state,null,2));}
  async function installed(plugin){try{await fsp.access(path.join(pluginsDir,plugin.id,plugin.entry));return true;}catch{return false;}}
  async function refreshBundled(plugin){const source=path.join(bundledDir,plugin.id),target=path.join(pluginsDir,plugin.id);await fsp.mkdir(target,{recursive:true});for(const name of [plugin.entry,'requirements.txt','README.md'])await fsp.copyFile(path.join(source,name),path.join(target,name));}
  async function list(){const state=await load(),result=[];for(const plugin of BUILT_IN_PLUGINS){const record=state.plugins[plugin.id]||{},isInstalled=await installed(plugin),active=processes.get(plugin.id),modelReady=plugin.model?await fsp.access(path.join(pluginsDir,plugin.id,'.model-ready')).then(()=>true).catch(()=>false):true;result.push({...plugin,installed:isInstalled,modelReady,enabled:Boolean(record.enabled&&isInstalled),configured:{...pluginDefaults(plugin),...(record.config||{})},status:active&&!active.killed?'running':runtime.get(plugin.id)?.status||'stopped',statusDetail:runtime.get(plugin.id)?.detail||''});}let names=[];try{names=await fsp.readdir(pluginsDir);}catch{}for(const name of names.filter((item)=>item.endsWith('.js'))){const id=`local:${name}`,record=state.plugins[id]||{};result.push({id,name:path.basename(name,'.js'),version:'Local',author:'Local file',category:'Automation',description:'Sandboxed JavaScript automation installed in the Pigeon plugins folder.',kind:'script',entry:name,installed:true,enabled:record.enabled!==false,configured:{},configSchema:[],status:'ready',statusDetail:''});}return result;}
  async function install(id){const plugin=BUILT_IN_PLUGINS.find((item)=>item.id===id);if(!plugin)throw new Error('Plugin is not in the available catalog');await fsp.mkdir(pluginsDir,{recursive:true});await fsp.cp(path.join(bundledDir,id),path.join(pluginsDir,id),{recursive:true,force:true});const state=await load(),record=state.plugins[id]||{};state.plugins[id]={...record,enabled:false,config:{...pluginDefaults(plugin),...(record.config||{})}};await save(state);runtime.set(id,{status:'installed',detail:'Plugin files installed. Enable it when setup is complete.'});return list();}
  async function setup(id){const plugin=BUILT_IN_PLUGINS.find((item)=>item.id===id);if(!plugin||!(await installed(plugin)))throw new Error('Install the plugin first');await refreshBundled(plugin);if(id!=='ai-removal')return list();const state=await load(),config={...pluginDefaults(plugin),...(state.plugins[id]?.config||{})},directory=path.join(pluginsDir,id),venv=path.join(directory,'.venv'),venvPython=process.platform==='win32'?path.join(venv,'Scripts','python.exe'):path.join(venv,'bin','python');runtime.set(id,{status:'installing',detail:'Creating a private Python environment…'});try{try{await fsp.access(venvPython);}catch{const python=await compatiblePython(config.pythonExecutable);await runCommand(python,['-m','venv',venv],directory);}runtime.set(id,{status:'installing',detail:'Downloading and installing the local AI model…'});await runCommand(venvPython,['-m','pip','install','-r',path.join(directory,'requirements.txt')],directory);runtime.set(id,{status:'installing',detail:'Downloading and preparing the compact Simple LaMa ONNX vision model…'});await runCommand(venvPython,[path.join(directory,'server.py'),'--prepare-model'],directory);runtime.set(id,{status:'ready',detail:'Simple LaMa ONNX is downloaded and ready. Enable the plugin to start it.'});}catch(error){runtime.set(id,{status:'error',detail:error.message});throw error;}return list();}
  function stop(id){const child=processes.get(id);if(child){processes.delete(id);child.kill();}runtime.set(id,{status:'stopped',detail:'Plugin is disabled.'});}
  async function start(id){const plugin=BUILT_IN_PLUGINS.find((item)=>item.id===id);if(!plugin||!(await installed(plugin)))throw new Error('Install the plugin first');await refreshBundled(plugin);if(processes.has(id))return;if(id==='ai-removal'){const state=await load(),config={...pluginDefaults(plugin),...(state.plugins[id]?.config||{})};if(!isLoopbackEndpoint(config.endpoint))throw new Error('AI Removal requires a loopback-only HTTP endpoint');const directory=path.join(pluginsDir,id),venvPython=process.platform==='win32'?path.join(directory,'.venv','Scripts','python.exe'):path.join(directory,'.venv','bin','python');let executable=venvPython;try{await fsp.access(executable);}catch{executable=await compatiblePython(config.pythonExecutable);}const endpoint=new URL(config.endpoint),child=spawn(executable,[path.join(directory,plugin.entry)],{cwd:directory,windowsHide:true,stdio:['ignore','ignore','pipe'],env:{...process.env,PIGEON_AI_REMOVAL_PORT:endpoint.port||'8765'}});processes.set(id,child);runtime.set(id,{status:'starting',detail:'Starting the local AI service…'});let error='';child.stderr.on('data',(chunk)=>{error=(error+String(chunk)).slice(-1200);});child.once('error',(reason)=>{processes.delete(id);runtime.set(id,{status:'error',detail:reason.message});});child.once('exit',(code)=>{if(processes.get(id)===child)processes.delete(id);runtime.set(id,{status:code===0?'stopped':'error',detail:error.trim()||`Plugin stopped with code ${code}`});});child.unref();setTimeout(()=>{if(processes.get(id)===child)runtime.set(id,{status:'running',detail:`Listening at ${config.endpoint}`});},900).unref?.();}}
  async function setEnabled(id,enabled){const state=await load(),plugins=await list(),plugin=plugins.find((item)=>item.id===id);if(!plugin)throw new Error('Plugin not found');if(!plugin.installed)throw new Error('Install the plugin first');state.plugins[id]={...(state.plugins[id]||{}),enabled:Boolean(enabled),config:{...(plugin.configured||{}),...(state.plugins[id]?.config||{})}};await save(state);if(enabled&&plugin.kind==='service')await start(id);if(!enabled&&plugin.kind==='service')stop(id);return list();}
  async function configure(id,config){const plugin=(await list()).find((item)=>item.id===id);if(!plugin)throw new Error('Plugin not found');const next={...plugin.configured};for(const field of plugin.configSchema||[]){if(Object.hasOwn(config||{},field.key))next[field.key]=field.type==='number'?Math.max(field.min||-Infinity,Math.min(field.max||Infinity,Number(config[field.key])||field.default)):String(config[field.key]??field.default);}if(id==='ai-removal'&&!isLoopbackEndpoint(next.endpoint))throw new Error('AI Removal requires a loopback-only HTTP endpoint');const state=await load(),wasEnabled=Boolean(state.plugins[id]?.enabled);state.plugins[id]={...(state.plugins[id]||{}),enabled:wasEnabled,config:next};await save(state);if(wasEnabled&&plugin.kind==='service'){stop(id);await start(id);}return list();}
  async function uninstall(id){const plugin=BUILT_IN_PLUGINS.find((item)=>item.id===id),state=await load();if(!plugin){const local=(await list()).find((item)=>item.id===id&&item.kind==='script');if(!local)throw new Error('Plugin not found');await fsp.rm(path.join(pluginsDir,path.basename(local.entry)),{force:true});delete state.plugins[id];await save(state);return list();}stop(id);await fsp.rm(path.join(pluginsDir,id),{recursive:true,force:true});delete state.plugins[id];await save(state);runtime.delete(id);return list();}
  async function configuration(id){return(await list()).find((item)=>item.id===id)?.configured||{};}
  async function restoreEnabled(){for(const plugin of await list())if(plugin.enabled&&plugin.kind==='service')start(plugin.id).catch((error)=>runtime.set(plugin.id,{status:'error',detail:error.message}));}
  function close(){for(const id of [...processes.keys()])stop(id);}
  return{list,install,setup,uninstall,setEnabled,configure,configuration,restoreEnabled,close};
}
module.exports={BUILT_IN_PLUGINS,createPluginManager,isLoopbackEndpoint,compatiblePython};
