const fsp=require('node:fs/promises');
const fs=require('node:fs');
const path=require('node:path');
const {spawn}=require('node:child_process');

const BUILT_IN_PLUGINS=[{id:'ai-removal',name:'AI Object Removal',version:'1.0.0',author:'Pigeon',category:'Image editing',description:'Remove painted objects with a private Simple LaMa vision-inpainting model running on this computer.',kind:'service',entry:'server.py',model:{name:'Simple LaMa ONNX',type:'Vision inpainting',size:'Approximately 200 MB',purpose:'Object removal and background reconstruction'},configSchema:[{key:'endpoint',label:'Local endpoint',type:'url',default:'http://127.0.0.1:8765/inpaint'},{key:'pythonExecutable',label:'Python 3.10/3.11 executable',type:'text',default:'auto'},{key:'brushSize',label:'Default mask brush size',type:'number',min:5,max:200,default:45}]}];
const LAMA_MODEL_URL='https://huggingface.co/Carve/LaMa-ONNX/resolve/main/lama_fp32.onnx',LAMA_MODEL_MIN_BYTES=150*1024*1024,LAMA_MODEL_MAX_BYTES=260*1024*1024;
const defaultState=()=>({plugins:{}});
function safeState(value){return value&&typeof value==='object'&&value.plugins&&typeof value.plugins==='object'?value:defaultState();}
function pluginDefaults(plugin){return Object.fromEntries((plugin.configSchema||[]).map((field)=>[field.key,field.default]));}
function isLoopbackEndpoint(value){try{const url=new URL(String(value));return url.protocol==='http:'&&['127.0.0.1','localhost','::1','[::1]'].includes(url.hostname);}catch{return false;}}
function runCommand(command,args,cwd,timeoutMs=600000){return new Promise((resolve,reject)=>{const child=spawn(command,args,{cwd,windowsHide:true,stdio:['ignore','pipe','pipe']}),output=[];let settled=false;const timer=setTimeout(()=>{child.kill();reject(new Error('Plugin setup timed out'));},timeoutMs);child.stdout.on('data',(chunk)=>output.push(String(chunk)));child.stderr.on('data',(chunk)=>output.push(String(chunk)));child.once('error',(error)=>{if(settled)return;settled=true;clearTimeout(timer);reject(error);});child.once('exit',(code)=>{if(settled)return;settled=true;clearTimeout(timer);code===0?resolve(output.join('').slice(-4000)):reject(new Error(output.join('').slice(-800)||`Plugin setup exited with code ${code}`));});});}
async function compatiblePython(configured='auto'){const requested=String(configured||'auto').trim(),check=async(executable,args=[])=>{try{const output=await runCommand(executable,[...args,'-c','import sys; print(sys.executable); print(f"{sys.version_info.major}.{sys.version_info.minor}")'],process.cwd(),20000),lines=output.trim().split(/\r?\n/),version=lines.at(-1);return['3.10','3.11'].includes(version)?lines.at(-2):null;}catch{return null;}};if(!['auto','python'].includes(requested.toLowerCase())){const found=await check(requested);if(found)return found;throw new Error('AI Object Removal requires Python 3.10 or 3.11. Update the configured Python executable.');}if(process.platform==='win32'){const launcher=await check('py',['-3.11']);if(launcher)return launcher;}try{const found=(await runCommand('uv',['python','find','3.11'],process.cwd(),20000)).trim().split(/\r?\n/).at(-1);if(found&&await check(found))return found;}catch{}const system=await check('python');if(system)return system;throw new Error('Python 3.10 or 3.11 was not found. Install Python 3.11 or configure its executable in Plugin Manager.');}
function createPluginManager({pluginsDir,bundledDir}){
  const stateFile=path.join(pluginsDir,'plugin-state.json'),processes=new Map(),runtime=new Map(),setRuntime=(id,status,detail)=>runtime.set(id,{status,detail});
  async function load(){try{return safeState(JSON.parse(await fsp.readFile(stateFile,'utf8')));}catch{return defaultState();}}
  async function save(state){await fsp.mkdir(pluginsDir,{recursive:true});await fsp.writeFile(stateFile,JSON.stringify(state,null,2));}
  async function installed(plugin){try{await fsp.access(path.join(pluginsDir,plugin.id,plugin.entry));return true;}catch{return false;}}
  async function refreshBundled(plugin){const source=path.join(bundledDir,plugin.id),target=path.join(pluginsDir,plugin.id);await fsp.mkdir(target,{recursive:true});for(const name of [plugin.entry,'requirements.txt','README.md'])await fsp.copyFile(path.join(source,name),path.join(target,name));}
  async function list(){const state=await load(),result=[];for(const plugin of BUILT_IN_PLUGINS){const record=state.plugins[plugin.id]||{},isInstalled=await installed(plugin),active=processes.get(plugin.id),modelReady=plugin.model?await fsp.access(path.join(pluginsDir,plugin.id,'.model-ready')).then(()=>true).catch(()=>false):true;result.push({...plugin,installed:isInstalled,modelReady,enabled:Boolean(record.enabled&&isInstalled),configured:{...pluginDefaults(plugin),...(record.config||{})},status:active&&!active.killed?'running':runtime.get(plugin.id)?.status||'stopped',statusDetail:runtime.get(plugin.id)?.detail||''});}let names=[];try{names=await fsp.readdir(pluginsDir);}catch{}for(const name of names.filter((item)=>item.endsWith('.js'))){const id=`local:${name}`,record=state.plugins[id]||{};result.push({id,name:path.basename(name,'.js'),version:'Local',author:'Local file',category:'Automation',description:'Sandboxed JavaScript automation installed in the Pigeon plugins folder.',kind:'script',entry:name,installed:true,enabled:record.enabled!==false,configured:{},configSchema:[],status:'ready',statusDetail:''});}return result;}
  async function downloadLamaModel(directory,id){const modelDirectory=path.join(directory,'models'),target=path.join(modelDirectory,'lama_fp32.onnx'),partial=`${target}.partial`;await fsp.mkdir(modelDirectory,{recursive:true});try{const stat=await fsp.stat(target);if(stat.size>=LAMA_MODEL_MIN_BYTES&&stat.size<=LAMA_MODEL_MAX_BYTES)return target;}catch{}let existing=0;try{existing=(await fsp.stat(partial)).size;if(existing>LAMA_MODEL_MAX_BYTES)existing=0;}catch{}const headers={'user-agent':'Pigeon-AI-Removal/1.1'};if(existing)headers.range=`bytes=${existing}-`;let response=await fetch(LAMA_MODEL_URL,{headers,signal:AbortSignal.timeout(900000)});if(existing&&response.status!==206){existing=0;await fsp.rm(partial,{force:true});response=await fetch(LAMA_MODEL_URL,{headers:{'user-agent':headers['user-agent']},signal:AbortSignal.timeout(900000)});}if(!response.ok||!response.body)throw new Error(`Model download failed with HTTP ${response.status}`);const contentRange=response.headers.get('content-range'),rangeTotal=Number(contentRange?.split('/').at(-1)),contentLength=Number(response.headers.get('content-length')),total=Number.isFinite(rangeTotal)?rangeTotal:existing+contentLength;if(!Number.isFinite(total)||total<LAMA_MODEL_MIN_BYTES||total>LAMA_MODEL_MAX_BYTES)throw new Error('The model download reported an unsafe size');const stream=fs.createWriteStream(partial,{flags:existing?'a':'w'}),reader=response.body.getReader();let received=existing,lastReported=-1;try{while(true){const{done,value}=await reader.read();if(done)break;received+=value.byteLength;if(received>LAMA_MODEL_MAX_BYTES)throw new Error('The model download exceeded the safety limit');if(!stream.write(Buffer.from(value)))await new Promise((resolve)=>stream.once('drain',resolve));const percent=Math.min(99,Math.floor(received/total*100));if(percent!==lastReported){lastReported=percent;setRuntime(id,'installing',`Downloading Simple LaMa ONNX · ${percent}% · ${Math.round(received/1024/1024)} of ${Math.round(total/1024/1024)} MB`);}}await new Promise((resolve,reject)=>stream.end((error)=>error?reject(error):resolve()));}catch(error){stream.destroy();throw error;}if(received<LAMA_MODEL_MIN_BYTES)throw new Error('The downloaded model is incomplete');await fsp.rename(partial,target);setRuntime(id,'installing','Model downloaded · validating with ONNX Runtime…');return target;}
  async function install(id){const plugin=BUILT_IN_PLUGINS.find((item)=>item.id===id);if(!plugin)throw new Error('Plugin is not in the available catalog');await fsp.mkdir(pluginsDir,{recursive:true});await fsp.cp(path.join(bundledDir,id),path.join(pluginsDir,id),{recursive:true,force:true});const state=await load(),record=state.plugins[id]||{};state.plugins[id]={...record,enabled:false,config:{...pluginDefaults(plugin),...(record.config||{})}};await save(state);setRuntime(id,'installed','Plugin files installed. Set up dependencies and model next.');return list();}
  async function setup(id){const plugin=BUILT_IN_PLUGINS.find((item)=>item.id===id);if(!plugin||!(await installed(plugin)))throw new Error('Install the plugin first');await refreshBundled(plugin);if(id!=='ai-removal')return list();const state=await load(),config={...pluginDefaults(plugin),...(state.plugins[id]?.config||{})},directory=path.join(pluginsDir,id),venv=path.join(directory,'.venv'),venvPython=process.platform==='win32'?path.join(venv,'Scripts','python.exe'):path.join(venv,'bin','python');setRuntime(id,'installing','Finding Python 3.10/3.11 and creating a private environment…');try{try{await fsp.access(venvPython);}catch{const python=await compatiblePython(config.pythonExecutable);await runCommand(python,['-m','venv',venv],directory);}setRuntime(id,'installing','Installing ONNX Runtime and image-processing dependencies…');await runCommand(venvPython,['-m','pip','install','-r',path.join(directory,'requirements.txt')],directory);await downloadLamaModel(directory,id);setRuntime(id,'installing','Validating the Simple LaMa ONNX model…');await runCommand(venvPython,[path.join(directory,'server.py'),'--prepare-model'],directory);setRuntime(id,'ready','Simple LaMa ONNX is downloaded and ready. Enable the plugin to start it.');}catch(error){setRuntime(id,'error',error.message);throw error;}return list();}
  function stop(id){const child=processes.get(id);if(child){processes.delete(id);child.kill();}setRuntime(id,'stopped','Plugin is disabled.');}
  async function start(id){const plugin=BUILT_IN_PLUGINS.find((item)=>item.id===id);if(!plugin||!(await installed(plugin)))throw new Error('Install the plugin first');await refreshBundled(plugin);if(processes.has(id))return;if(id==='ai-removal'){const state=await load(),config={...pluginDefaults(plugin),...(state.plugins[id]?.config||{})};if(!isLoopbackEndpoint(config.endpoint))throw new Error('AI Removal requires a loopback-only HTTP endpoint');const directory=path.join(pluginsDir,id),venvPython=process.platform==='win32'?path.join(directory,'.venv','Scripts','python.exe'):path.join(directory,'.venv','bin','python');let executable=venvPython;try{await fsp.access(executable);}catch{executable=await compatiblePython(config.pythonExecutable);}const endpoint=new URL(config.endpoint),child=spawn(executable,[path.join(directory,plugin.entry)],{cwd:directory,windowsHide:true,stdio:['ignore','ignore','pipe'],env:{...process.env,PIGEON_AI_REMOVAL_PORT:endpoint.port||'8765'}});processes.set(id,child);setRuntime(id,'starting','Loading Simple LaMa ONNX and starting the local service…');let error='';child.stderr.on('data',(chunk)=>{error=(error+String(chunk)).slice(-1200);});child.once('error',(reason)=>{processes.delete(id);setRuntime(id,'error',reason.message);});child.once('exit',(code)=>{if(processes.get(id)===child)processes.delete(id);setRuntime(id,code===0?'stopped':'error',error.trim()||`Plugin stopped with code ${code}`);});child.unref();setTimeout(()=>{if(processes.get(id)===child)setRuntime(id,'running',`Simple LaMa ONNX is listening at ${config.endpoint}`);},900).unref?.();}}
  async function setEnabled(id,enabled){const state=await load(),plugins=await list(),plugin=plugins.find((item)=>item.id===id);if(!plugin)throw new Error('Plugin not found');if(!plugin.installed)throw new Error('Install the plugin first');state.plugins[id]={...(state.plugins[id]||{}),enabled:Boolean(enabled),config:{...(plugin.configured||{}),...(state.plugins[id]?.config||{})}};await save(state);if(enabled&&plugin.kind==='service')await start(id);if(!enabled&&plugin.kind==='service')stop(id);return list();}
  async function configure(id,config){const plugin=(await list()).find((item)=>item.id===id);if(!plugin)throw new Error('Plugin not found');const next={...plugin.configured};for(const field of plugin.configSchema||[]){if(Object.hasOwn(config||{},field.key))next[field.key]=field.type==='number'?Math.max(field.min||-Infinity,Math.min(field.max||Infinity,Number(config[field.key])||field.default)):String(config[field.key]??field.default);}if(id==='ai-removal'&&!isLoopbackEndpoint(next.endpoint))throw new Error('AI Removal requires a loopback-only HTTP endpoint');const state=await load(),wasEnabled=Boolean(state.plugins[id]?.enabled);state.plugins[id]={...(state.plugins[id]||{}),enabled:wasEnabled,config:next};await save(state);if(wasEnabled&&plugin.kind==='service'){stop(id);await start(id);}return list();}
  async function uninstall(id){const plugin=BUILT_IN_PLUGINS.find((item)=>item.id===id),state=await load();if(!plugin){const local=(await list()).find((item)=>item.id===id&&item.kind==='script');if(!local)throw new Error('Plugin not found');await fsp.rm(path.join(pluginsDir,path.basename(local.entry)),{force:true});delete state.plugins[id];await save(state);return list();}stop(id);await fsp.rm(path.join(pluginsDir,id),{recursive:true,force:true});delete state.plugins[id];await save(state);runtime.delete(id);return list();}
  async function configuration(id){return(await list()).find((item)=>item.id===id)?.configured||{};}
  async function restoreEnabled(){for(const plugin of await list())if(plugin.enabled&&plugin.kind==='service')start(plugin.id).catch((error)=>setRuntime(plugin.id,'error',error.message));}
  function close(){for(const id of [...processes.keys()])stop(id);}
  return{list,install,setup,uninstall,setEnabled,configure,configuration,restoreEnabled,close};
}
module.exports={BUILT_IN_PLUGINS,createPluginManager,isLoopbackEndpoint,compatiblePython};
