"use strict";
const fs=require('node:fs'),fsp=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {spawn,execFile}=require('node:child_process');
const {budget,systemCpuDelta,contentFingerprint,fingerprint,admissible,normalizeIdleMinutes}=require('./semantic-policy');
const {createSemanticGovernor}=require('./semantic-governor');
const {createSemanticWorkQueue}=require('./semantic-priority');
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const REQUIREMENTS=['sentence-transformers==6.1.0','transformers==5.19.0','pillow==12.3.0','soundfile==0.14.0','psutil==7.2.2','pypdf==6.19.0','pypdfium2==5.9.0','python-docx==1.2.0','openpyxl==3.1.5'];
function createSemanticService({userData,getContext,getAssets,getAsset=null,getLocations=()=>[],resolveScope=null,getIdleSeconds=()=>0,getIdleMinutes=()=>10,createGovernor=createSemanticGovernor,ffmpeg,emit=()=>{},report=()=>{},registerPause=()=>()=>{},diagnostic=()=>{}}){
  let scopeQueue=[],scopeRevision=0,currentLocationPlan=null,activePhase='portfolio';
  let priorityIds=new Set(),knownFingerprints=new Map(),dirtyAssets=new Map(),pendingSync=new Set(),syncTimer=null,syncing=false,activeAction='';
  let scopeName='',scopeMode='',searching=false,healthyPython='',runtimeOverride='',setupRetryAfter=0,setupScope='';
  let contextKey='',epoch=0,child=null,governor=null,ready=null,sequence=0,pending=new Map(),queue=[],draining=false,indexing=false,paused=false,manual=false,closed=false,setupPromise=null,setupChild=null,settings={automatic:true},info={indexed:0,limited:0,vectors:0},lastCpus=os.cpus(),systemBusy=1,indexDone=false,releasePause=()=>{},lastSearch=Date.now();
  let status={state:'unavailable',detail:'The local engine will be checked and prepared automatically.',completed:0,total:0,current:'',error:'',resources:{}};
  const managed=path.join(userData,'semantic-runtime'),globalConfig=path.join(userData,'semantic-runtime.json');
  function runtimePython(){let configured='';try{configured=JSON.parse(fs.readFileSync(globalConfig,'utf8')).python||'';}catch{}const dev=path.join(__dirname,'..','.semantic-runtime',process.platform==='win32'?'Scripts/python.exe':'bin/python');return runtimeOverride||process.env.PIGEON_SEMANTIC_PYTHON||configured||(fs.existsSync(dev)?dev:path.join(managed,process.platform==='win32'?'Scripts/python.exe':'bin/python'));}
  function selectedBudget(mode){return budget(mode,os.cpus().length,os.totalmem(),settings.resourcePercent??15);}
  function idleMinutes(){return normalizeIdleMinutes(getIdleMinutes());}
  function automaticIdleBlocked(){return !manual&&getIdleSeconds()<idleMinutes()*60;}
  function waitForIdle(){publish({state:'waiting',waitReason:'activity',detail:`Automatic analysis waits until your computer has been unused for ${idleMinutes()} minutes. Analyze now starts immediately within your resource cap.`});}
  function saveSettings(){const c=getContext();if(c?.databaseFile)fs.writeFileSync(c.databaseFile+'.semantic-settings.json',JSON.stringify(settings));}
  function snapshot(){const context=getContext(),total=currentAssets().length;return{...status,...info,total,completed:Math.min(total,Math.max(status.completed||0,(info.indexed||0)+(info.limited||0))),portfolioId:context?.portfolioId,automatic:settings.automatic!==false,pauseOnActivity:true,idleMinutes:idleMinutes(),idleSeconds:getIdleSeconds(),currentScope:scopeQueue[0]?.label||currentLocationPlan?.label||'',queuedScopes:scopeQueue.slice(1).map(job=>job.label),analysisPhase:activePhase,activityPaused:!manual&&(status.waitReason==='activity'||(indexing&&status.resources?.activityBlocked))&&(dirtyAssets.size>0||Math.max(status.completed||0,(info.indexed||0)+(info.limited||0))<total),changedItems:dirtyAssets.size,resourcePercent:settings.resourcePercent??15,paused,mode:manual?'manual':'automatic',model:'EmbeddingGemma 2',runtimeReady:fs.existsSync(runtimePython()),policy:{automatic:{cpu:settings.resourcePercent??15,memory:settings.resourcePercent??15},manual:{cpu:settings.resourcePercent??15,memory:settings.resourcePercent??15}},systemCpuPercent:Math.round(systemBusy*100)};}
  function publish(patch={}){Object.assign(status,patch);emit(snapshot());}
  function killEngine(reason='Semantic work stopped'){
    governor?.close({terminate:true});governor=null;releasePause();releasePause=()=>{};const old=child;child=null;ready=null;
    for(const {reject,timer} of pending.values()){clearTimeout(timer);reject(Error(reason));}pending.clear();for(const job of queue.splice(0))job.reject(Error(reason));
    if(scopeName){execFile('systemctl',['--user','kill','--signal=SIGKILL',scopeName],{timeout:3000},()=>{});scopeName='';scopeMode='';}
    if(old?.pid)try{if(process.platform!=='win32')process.kill(-old.pid,'SIGKILL');else old.kill('SIGKILL');}catch{}
  }
  function context(){const c=getContext();if(!c?.databaseFile||c.loading)return null;const key=JSON.stringify([c.portfolioId,c.databaseFile]);if(key!==contextKey){epoch++;killEngine('Portfolio changed');contextKey=key;priorityIds=new Set();paused=false;manual=false;indexDone=false;info={indexed:0,limited:0,vectors:0};settings={automatic:true,resourcePercent:15,pauseOnActivity:true};try{settings={...settings,...JSON.parse(fs.readFileSync(c.databaseFile+'.semantic-settings.json','utf8'))};}catch{}settings.pauseOnActivity=true;manual=Boolean(settings.resumeRequested);paused=Boolean(settings.paused);scopeQueue=Array.isArray(settings.scanQueue)?settings.scanQueue.filter(job=>job&&Array.isArray(job.directIds)&&Array.isArray(job.descendantIds)).slice(0,64):[];if(!scopeQueue.length&&settings.priorityIds?.length)scopeQueue=[{key:'legacy-selection',scope:null,label:'Saved selection',directIds:settings.priorityIds,descendantIds:[]}];currentLocationPlan=null;activePhase='portfolio';scopeRevision++;priorityIds=new Set(scopeQueue.flatMap(job=>[...job.directIds,...job.descendantIds]));knownFingerprints=new Map(currentAssets().map(asset=>[asset.id,fingerprint(asset)]));dirtyAssets=new Map((settings.changedIds||[]).map(id=>[id,knownFingerprints.get(id)]));pendingSync=new Set(dirtyAssets.keys());clearTimeout(syncTimer);syncTimer=null;if(pendingSync.size)scheduleSync();publish({state:paused?'paused':'idle',completed:0,total:0,current:'',error:'',waitReason:null,resources:{},activeFiles:[],detail:'Portfolio index loaded. Saved analysis resumes from its checkpoints.'});}return c;}
  function persistScopeQueue(){settings.scanQueue=scopeQueue.map(job=>({...job,directIds:[...job.directIds],descendantIds:[...job.descendantIds]}));priorityIds=new Set(scopeQueue.flatMap(job=>[...job.directIds,...job.descendantIds]));settings.priorityIds=[...priorityIds];saveSettings();}
  function refreshScopePlans(){if(resolveScope)scopeQueue=scopeQueue.map(job=>job.scope||job.key==='portfolio'?resolveScope(job.scope):job);persistScopeQueue();}
  function interruptedLocation(asset,assets){const location=getLocations().find(item=>item.id===asset.locationId);if(location&&resolveScope)return resolveScope({type:'folder',id:location.id,subfolder:''});return{key:'location:'+(asset.locationId||path.dirname(asset.path)),scope:null,label:location?.name||path.dirname(asset.path),directIds:assets.filter(item=>asset.locationId?item.locationId===asset.locationId:path.dirname(item.path)===path.dirname(asset.path)).map(item=>item.id),descendantIds:[]};}
  function currentAssets(){return getAssets().filter(admissible);}
  function assetRecord(asset){const imageExtensions=new Set(['.png','.jpg','.jpeg','.webp','.gif','.bmp','.tif','.tiff']);return{id:asset.id,path:asset.path,kind:asset.kind,size:asset.size,modified:asset.modified,name:asset.name||asset.filename,note:asset.note||'',tags:Array.isArray(asset.tags)?[...asset.tags]:[],imagePath:asset.kind==='image'?(asset.editedPath||asset.editedPreviewPath||asset.proxyPath||(!imageExtensions.has(path.extname(asset.path).toLowerCase())?asset.thumbnailPath:null)||asset.path):null};}
  function assetFingerprints(assets=currentAssets()){return Object.fromEntries(assets.map(a=>[a.id,fingerprint(a)]));}
  function syncRecord(asset){return{asset:assetRecord(asset),fingerprint:fingerprint(asset),contentFingerprint:contentFingerprint(asset)};}
  function persistChanges(){settings.changedIds=[...dirtyAssets.keys()];saveSettings();}
  function scheduleSync(delay=50){if(syncTimer||closed)return;syncTimer=setTimeout(()=>{syncTimer=null;void syncChanges();},delay);syncTimer.unref();}
  function assetsChanged(assets){if(closed||!context())return;for(const asset of Array.isArray(assets)?assets:[assets]){if(!asset?.id)continue;const current=getAsset?getAsset(asset.id):asset,key=current&&admissible(current)?fingerprint(current):null;if(knownFingerprints.get(asset.id)===key)continue;knownFingerprints.set(asset.id,key);dirtyAssets.set(asset.id,key);pendingSync.add(asset.id);scopeRevision++;}if(pendingSync.size)scheduleSync();}
  async function syncChanges(){if(closed||syncing||!pendingSync.size)return;if(healthyPython!==runtimePython()&&automaticIdleBlocked()){persistChanges();scheduleSync(5000);return;}syncing=true;const session=epoch,ids=[...pendingSync].slice(0,256);for(const id of ids)pendingSync.delete(id);try{persistChanges();await ensureReady();if(session!==epoch||closed)return;const records=[],removedIds=[];for(const id of ids){const asset=getAsset?getAsset(id):getAssets().find(item=>item.id===id);if(asset&&admissible(asset))records.push(syncRecord(asset));else{removedIds.push(id);dirtyAssets.delete(id);}}const next=await request('sync-assets',{records,removedIds},true);if(session!==epoch||closed)return;info=next;publish({detail:'Metadata changes saved. Updated tags and edited images are queued for analysis.'});if(!paused)void runIndex();}catch(error){if(session===epoch&&!closed){for(const id of ids)pendingSync.add(id);diagnostic('warning','Semantic metadata synchronization delayed',error.message);}}finally{syncing=false;if(pendingSync.size)scheduleSync(healthyPython?50:5000);}}
  function startEngine(){
    if(ready)return ready;
    const c=context();if(!c)throw Error('Wait for the active portfolio to load');const python=runtimePython();if(!fs.existsSync(python))throw Error('The local engine runtime is missing');
    const p=selectedBudget(manual||searching?'manual':'automatic');let readyResolve,readyReject;const session=epoch;
    ready=new Promise((resolve,reject)=>{readyResolve=resolve;readyReject=reject;});ready.catch(()=>{});
    const engineArgs=['-u',path.join(__dirname,'semantic-engine.py').replace('app.asar'+path.sep,'app.asar.unpacked'+path.sep),c.databaseFile+'.semantic.sqlite3'];
    const hardCaps=process.platform==='linux'&&fs.existsSync('/usr/bin/systemd-run');
    scopeName=hardCaps?`pigeon-semantic-${process.pid}-${Date.now()}.scope`:'';scopeMode=manual||searching?'manual':'automatic';
    const launchArgs=hardCaps?['--user','--scope','--quiet','--collect',`--unit=${scopeName}`,'-p',`CPUQuota=${(p.cpu*p.cores*100).toFixed(2)}%`,'-p','CPUQuotaPeriodSec=100ms','-p',`MemoryMax=${p.memoryBytes}`,'-p','MemorySwapMax=0','-p','TasksMax=128','--',python,...engineArgs]:engineArgs;
    status.hardCaps=hardCaps;
    const engine=spawn(hardCaps?'/usr/bin/systemd-run':python,launchArgs,{detached:process.platform!=='win32',windowsHide:true,stdio:['pipe','pipe','pipe'],env:{...process.env,CUDA_VISIBLE_DEVICES:'',PIGEON_SEMANTIC_THREADS:String(p.threads),PIGEON_SEMANTIC_FFMPEG:ffmpeg,OMP_NUM_THREADS:String(p.threads),MKL_NUM_THREADS:String(p.threads),OPENBLAS_NUM_THREADS:'1',TOKENIZERS_PARALLELISM:'false'}});child=engine;
    const bootTimer=setTimeout(()=>{readyReject(Error('Semantic engine startup timed out'));killEngine('Semantic engine startup timed out');},30000);
    let buffer='',errors='';engine.stderr.on('data',data=>{errors=(errors+data).slice(-5000);});
    engine.stdout.on('data',data=>{buffer+=data;if(buffer.length>16*1024*1024){killEngine('Semantic engine response exceeded safety limit');return;}let index;while((index=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,index);buffer=buffer.slice(index+1);try{const message=JSON.parse(line);if(message.ready){clearTimeout(bootTimer);readyResolve();}else if(message.progress&&pending.has(message.id)){publish({searchProgress:message.progress});}else if(pending.has(message.id)){const job=pending.get(message.id);pending.delete(message.id);clearTimeout(job.timer);if(message.error)job.reject(Error(message.error));else job.resolve(message.result);}}catch(error){diagnostic('warning','Invalid semantic engine response',error.message);}}});
    engine.on('error',error=>{clearTimeout(bootTimer);readyReject(error);if(child===engine){killEngine(error.message);publish({state:'error',error:error.message,detail:'Local semantic engine could not start.'});}});
    engine.on('exit',(code,signal)=>{clearTimeout(bootTimer);readyReject(Error(errors||`Semantic engine exited (${code||signal})`));if(child===engine){killEngine('Semantic engine exited');if(session===epoch)publish({state:'error',error:errors.slice(-700)||'Engine stopped',detail:'The engine stopped. Its installation will be checked before the next operation.'});}});
    governor=createGovernor({child:engine,python,getMode:()=>manual||searching?'manual':'automatic',getBudget:()=>selectedBudget(manual||searching?'manual':'automatic'),isPaused:()=>paused&&!['sync-assets','prune','plan','info'].includes(activeAction),pauseOnActivity:()=>!['sync-assets','prune','plan','info'].includes(activeAction),isBusy:automaticIdleBlocked,onMemoryLimit:error=>{killEngine(error.message);paused=true;publish({state:'error',waitReason:null,error:error.message,detail:'The worker reached its actual memory cap. Increase Resource limit and choose Analyze now to retry.'});},onMonitorError:error=>{killEngine(error.message);paused=true;publish({state:'error',waitReason:null,error:error.message,detail:'Could not monitor the worker resource cap. Choose Analyze now to retry.'});},onSample:resources=>{status.resources=resources;}});
    const id=`${c.portfolioId}:semantic-index`;releasePause=registerPause(id,value=>{paused=Boolean(value);publish({state:paused?'paused':'waiting'});});
    return ready;
  }
  function request(action,payload={},priority=false){return new Promise((resolve,reject)=>{const job={action,payload,resolve,reject,epoch};if(priority)queue.unshift(job);else queue.push(job);void drain();});}
  async function drain(){if(draining||closed)return;draining=true;try{while(queue.length&&!closed){const job=queue.shift();if(job.epoch!==epoch){job.reject(Error('Portfolio changed'));continue;}try{activeAction=job.action;await startEngine();if(job.epoch!==epoch)throw Error('Portfolio changed');const id=++sequence;const result=await new Promise((resolve,reject)=>{let timer;const expire=()=>{const operation=pending.get(id);if(!operation)return;const metadata=['sync-assets','prune','plan','info'].includes(job.action);if((paused&&!metadata)||(job.action==='index_batch'&&!searching&&automaticIdleBlocked())){timer=setTimeout(expire,600000);operation.timer=timer;return;}pending.delete(id);reject(Error('Semantic operation timed out'));killEngine('Semantic operation timed out');};timer=setTimeout(expire,600000);pending.set(id,{resolve,reject,timer});child.stdin.write(JSON.stringify({id,action:job.action,...job.payload})+'\n',error=>{if(error){clearTimeout(timer);pending.delete(id);reject(error);}});});job.resolve(result);}catch(error){job.reject(error);}}}finally{activeAction='';draining=false;}}
  async function runIndex(){
    const c=context();if(!c||indexing||paused||closed||setupPromise)return;if(!manual&&settings.automatic===false)return;
    if(automaticIdleBlocked()){waitForIdle();return;}
    if(healthyPython!==runtimePython()){if(Date.now()>=setupRetryAfter)void ensureReady().then(()=>runIndex()).catch(()=>{});return;}
    indexing=true;const session=epoch,progressId=`${c.portfolioId}:semantic-index`;
    let rerun=false,assets=currentAssets(),revision=scopeRevision,tiers=[];
    try{
      refreshScopePlans();
      info=await request('prune',{assets:assetFingerprints(assets),records:assets.map(syncRecord)},true);
      const pendingIds=new Set((await request('plan')).pending);
      const work=createSemanticWorkQueue(assets.filter(a=>pendingIds.has(a.id)&&(manual||settings.automatic!==false||dirtyAssets.has(a.id))),{groupRemainingByLocation:true});
      if(!work.length&&revision===scopeRevision){scopeQueue=[];currentLocationPlan=null;persistScopeQueue();for(const [id,key]of dirtyAssets)if(!pendingIds.has(id)&&key===knownFingerprints.get(id))dirtyAssets.delete(id);persistChanges();manual=false;settings.resumeRequested=false;saveSettings();await applyKernelBudget();publish({state:'idle',detail:'Portfolio index is up to date.',completed:assets.length,total:assets.length,current:'',error:''});return;}
      let completed=assets.length-work.length;
      publish({state:'indexing',detail:'Analyzing files in parallel batches, sharing one local model.',completed,total:assets.length,error:''});
      while(true){
        if(closed||session!==epoch)return;
        if(revision!==scopeRevision){revision=scopeRevision;assets=currentAssets();refreshScopePlans();info=await request('prune',{assets:assetFingerprints(assets),records:assets.map(syncRecord)},true);const pendingIds=new Set((await request('plan')).pending);work.replace(assets.filter(asset=>pendingIds.has(asset.id)&&(manual||settings.automatic!==false||dirtyAssets.has(asset.id))));completed=assets.length-work.length;tiers=[];}
        if(!tiers.length){tiers=scopeQueue.flatMap(job=>[new Set(job.directIds),new Set(job.descendantIds)]);if(!tiers.length)tiers=[new Set(dirtyAssets.keys())];work.prioritizeTiers(tiers);}
        if(scopeQueue.length){const tier=work.activeTierIndex,finished=tier<0?scopeQueue.length:Math.floor(tier/2);if(finished){scopeQueue.splice(0,finished);persistScopeQueue();tiers=scopeQueue.flatMap(job=>[new Set(job.directIds),new Set(job.descendantIds)]);if(!tiers.length)tiers=[new Set(dirtyAssets.keys())];work.prioritizeTiers(tiers);}activePhase=scopeQueue.length&&work.activeTierIndex%2?'subfolders':scopeQueue.length?'direct':'portfolio';}
        if(!work.length)break;
        if(paused||(!manual&&settings.automatic===false)){publish({state:'paused',detail:'Analysis paused. Completed work is saved.'});return;}
        const batchBudget=selectedBudget(manual?'manual':'automatic');
        if(automaticIdleBlocked()){waitForIdle();await sleep(1000);continue;}
        const headroom=batchBudget.memoryBytes-(status.resources?.memoryBytes||0),workers=Math.min(batchBudget.fileWorkers,Math.max(1,Math.floor((headroom-32*1024*1024)/(96*1024*1024))));
        const batch=work.take(workers),valid=batch.filter(asset=>{const current=getAsset?getAsset(asset.id):getAssets().find(item=>item.id===asset.id);return current&&admissible(current)&&fingerprint(current)===fingerprint(asset);});
        completed+=batch.length-valid.length;if(!valid.length)continue;
        currentLocationPlan=scopeQueue.length?null:interruptedLocation(valid[0],assets);
        const names=valid.map(asset=>asset.name||asset.filename);
        publish({state:'indexing',waitReason:null,current:names.join(' · '),activeFiles:names,fileWorkers:workers,completed});
        report(progressId,{label:'Semantic analysis',detail:`${valid.length} files in batch: ${names.join(' · ')}`,completed,total:assets.length});
        const jobs=valid.map(asset=>({asset:assetRecord(asset),fingerprint:fingerprint(asset)})),submitted=new Map(jobs.map(job=>[job.asset.id,job.fingerprint]));
        const result=await request('index_batch',{jobs,workers,steps:1,memoryLimit:batchBudget.memoryBytes});
        info=result.info||info;const outcomes=new Map(result.results.map(item=>[item.id,item]));
        for(const asset of valid){const item=outcomes.get(asset.id);if(!item)throw Error('Semantic batch returned an incomplete response');if(item.done){completed++;if(dirtyAssets.get(asset.id)===submitted.get(asset.id)&&fingerprint(asset)===submitted.get(asset.id))dirtyAssets.delete(asset.id);}else work.push(asset);if(item.error)status.lastFileError=item.error;}
        if(settings.changedIds?.length)persistChanges();publish({completed,activeFiles:[],current:''});
        await sleep(manual?25:100);
      }
      info=await request('info');if(revision!==scopeRevision){rerun=true;return;}scopeQueue=[];currentLocationPlan=null;activePhase='portfolio';persistScopeQueue();indexDone=true;manual=false;settings.resumeRequested=false;saveSettings();await applyKernelBudget();publish({state:'idle',detail:'Portfolio analysis complete. New or changed files are picked up automatically.',current:'',activeFiles:[],fileWorkers:0});report(progressId,{label:'Semantic analysis',completed:assets.length,total:assets.length,done:true});
    }catch(error){if(session===epoch&&!closed){if(/No module named|local_files_only|model cache|cannot find|does not exist/i.test(error.message)){healthyPython='';setupRetryAfter=0;}publish({state:'error',error:error.message,detail:'Analysis stopped. Completed vectors are retained.',activeFiles:[],current:'',fileWorkers:0});report(progressId,{label:'Semantic analysis',detail:error.message,done:true,status:'error'});}}
    finally{indexing=false;if(rerun&&session===epoch&&!closed)void runIndex();}
  }
  const ticker=setInterval(()=>{if(closed)return;const cpus=os.cpus(),delta=systemCpuDelta(lastCpus,cpus);lastCpus=cpus;if(delta!==null)systemBusy=delta;context();if(!indexing){if(indexDone){indexDone=false;}void runIndex();}},5000);ticker.unref();
  const heartbeat=setInterval(()=>{if(child&&Date.now()-lastSearch>180000&&!indexing&&!pending.size&&!queue.length)killEngine('Idle engine unloaded');if(indexing||status.state==='waiting')emit(snapshot());},1000);heartbeat.unref();
  async function getStatus(){context();if(!closed&&!paused&&settings.automatic!==false&&automaticIdleBlocked()&&!indexing&&!setupPromise)waitForIdle();if(!closed&&!paused&&!setupPromise&&(manual||settings.automatic!==false&&!automaticIdleBlocked())&&healthyPython!==runtimePython()&&Date.now()>=setupRetryAfter)void ensureReady().then(()=>runIndex()).catch(()=>{});if(child&&!pending.size&&!queue.length)try{info=await request('info',{},true);}catch{}return snapshot();}
  async function configure(input={}){const c=context();if(!c)throw Error('Wait for portfolio loading');if(typeof input.automatic==='boolean'){settings.automatic=input.automatic;paused=false;settings.paused=false;}if(Number.isFinite(input.resourcePercent))settings.resourcePercent=Math.max(5,Math.min(50,Math.round(input.resourcePercent)));await fsp.writeFile(c.databaseFile+'.semantic-settings.json',JSON.stringify(settings));if(settings.automatic===false&&!manual&&indexing){epoch++;killEngine('Automatic analysis disabled');}indexDone=false;await applyKernelBudget();publish({state:settings.automatic===false&&!manual?'idle':'waiting',detail:settings.automatic===false?'Automatic analysis disabled. Search and Analyze now remain available.':'Automatic analysis enabled.'});if(pendingSync.size)scheduleSync();if(!paused)void runIndex();return snapshot();}
async function applyKernelBudget(){const mode=manual||searching?'manual':'automatic';const key=mode+':'+(settings.resourcePercent??15);if(!scopeName||scopeMode===key)return;const p=selectedBudget(mode),scope=scopeName;await new Promise((resolve,reject)=>execFile('systemctl',['--user','set-property','--runtime',scope,`CPUQuota=${(p.cpu*p.cores*100).toFixed(2)}%`,`MemoryMax=${p.memoryBytes}`],{timeout:5000},error=>error?reject(error):resolve()));if(scopeName===scope)scopeMode=key;}
  async function start(input={}){const c=context();if(!c)throw Error('Wait for portfolio loading');if(input.portfolioId&&input.portfolioId!==c.portfolioId)throw Error('Portfolio changed before analysis started');const ids=Array.isArray(input.priorityIds)?input.priorityIds:[],incoming=input.priorityPlan||{key:ids.length?'selection:'+JSON.stringify(ids):'portfolio',scope:null,label:ids.length?'Selected scope':'Portfolio',directIds:ids.length?ids:currentAssets().map(asset=>asset.id),descendantIds:[]},interrupted=scopeQueue[0]||(indexing?currentLocationPlan:null);scopeQueue=[incoming,...scopeQueue.slice(1).filter(job=>job.key!==incoming.key),...(interrupted&&interrupted.key!==incoming.key?[interrupted]:[])].slice(0,64);scopeRevision++;currentLocationPlan=null;activePhase='direct';persistScopeQueue();const session=epoch;manual=true;paused=false;settings.resumeRequested=true;settings.paused=false;settings.priorityIds=[...priorityIds];saveSettings();await ensureReady();if(session!==epoch)throw Error('Portfolio changed during engine preparation');await applyKernelBudget();publish({state:'waiting',waitReason:null,error:'',resources:{},detail:'Starting now within your resource cap. Selected scope first: direct items, then subfolders, then queued locations, then remaining portfolio.'});void runIndex();return snapshot();}
  async function continueAnalysis(){const c=context();if(!c)throw Error('Wait for portfolio loading');const session=epoch;paused=false;manual=true;settings.paused=false;settings.resumeRequested=true;saveSettings();await ensureReady();if(session!==epoch)throw Error('Portfolio changed during engine preparation');await applyKernelBudget();publish({state:'waiting',waitReason:null,error:'',resources:{},detail:'Resuming now within your resource cap.'});void runIndex();return snapshot();}
  function pause(value=true){context();paused=Boolean(value);settings.paused=paused;saveSettings();publish({state:paused?'paused':'waiting',detail:paused?'Analysis paused. Search remains available after resume.':'Analysis resumed.'});if(!paused)void runIndex();return snapshot();}
  async function search(input={}){
    const c=context();if(!c)throw Error('Wait for the portfolio to load');if(paused)throw Error('Resume semantic analysis before searching');lastSearch=Date.now();const session=epoch;
    const assets=currentAssets().filter(a=>!input.kind||a.kind===input.kind);let sample=input.sample||null;if(input.assetId){const asset=currentAssets().find(a=>a.id===input.assetId);if(!asset)throw Error('Sample is unavailable or locked');sample=assetRecord(asset);}
    if(input.query&&typeof input.query!=='string')throw Error('Search text must be a string');
    let result,sentFingerprints;searching=true;publish({searchProgress:{stage:'Preparing query',completed:0,total:0}});try{await ensureReady();if(session!==epoch)throw Error('Portfolio changed during engine preparation');await applyKernelBudget();sentFingerprints=assetFingerprints(assets);result=await request('search',{query:String(input.query||'').slice(0,4000),sample,assetId:input.assetId,minimum:input.minimum,limit:input.limit,offset:input.offset,assets:sentFingerprints},true);}catch(error){if(/No module named|local_files_only|model cache|cannot find|does not exist/i.test(error.message))healthyPython='';throw error;}finally{searching=false;publish({searchProgress:null});await applyKernelBudget();}
    if(session!==epoch)throw Error('Portfolio changed during search');const fresh=new Map(currentAssets().map(a=>[a.id,a]));
    return{...result,portfolioId:c.portfolioId,results:result.results.filter(r=>fresh.has(r.id)&&fingerprint(fresh.get(r.id))===sentFingerprints[r.id]).map(r=>({...r,asset:fresh.get(r.id)}))};
  }
  async function runSetupCommand(command,args,{quiet=false,timeout=0}={}){
    if(closed)throw Error('Pigeon is closing');
    const p=selectedBudget(manual||searching?'manual':'automatic'),hardCaps=process.platform==='linux'&&fs.existsSync('/usr/bin/systemd-run');
    const scope=`pigeon-semantic-setup-${process.pid}-${Date.now()}.scope`;
    const scoped=hardCaps?['--user','--scope','--quiet','--collect',`--unit=${scope}`,'-p',`CPUQuota=${(p.cpu*p.cores*100).toFixed(2)}%`,'-p','CPUQuotaPeriodSec=100ms','-p',`MemoryMax=${p.memoryBytes}`,'-p','MemorySwapMax=0','--',command,...args]:args;
    await new Promise((resolve,reject)=>{const processChild=spawn(hardCaps?'/usr/bin/systemd-run':command,scoped,{windowsHide:true,stdio:['ignore','pipe','pipe'],env:{...process.env,CUDA_VISIBLE_DEVICES:'',OMP_NUM_THREADS:'1',MKL_NUM_THREADS:'1',OPENBLAS_NUM_THREADS:'1',TOKENIZERS_PARALLELISM:'false',UV_CONCURRENT_DOWNLOADS:'1',UV_CONCURRENT_BUILDS:'1',UV_CONCURRENT_INSTALLS:'1'}});setupChild=processChild;setupScope=hardCaps?scope:'';let output='',timer=null;
      if(timeout)timer=setTimeout(()=>{if(hardCaps)execFile('systemctl',['--user','kill','--signal=SIGKILL',scope],{timeout:3000},()=>{});processChild.kill('SIGKILL');reject(Error('Local engine health check timed out'));},timeout);
      for(const stream of [processChild.stdout,processChild.stderr])stream.on('data',data=>{output=(output+data).slice(-3000);if(!quiet)publish({state:'setup',detail:output.split(/\r?\n/).filter(Boolean).at(-1)||'Preparing local engine…'});});
      processChild.on('error',error=>{clearTimeout(timer);reject(error);});processChild.on('exit',code=>{clearTimeout(timer);if(setupChild===processChild){setupChild=null;setupScope='';}code===0?resolve():reject(Error(output.slice(-1000)||`Setup exited ${code}`));});});
  }
  const dependencyCheck='import torch, torchvision; assert torch.version.cuda is None; assert torch.__version__.split("+")[0] == "2.14.1"; assert torchvision.__version__.split("+")[0] == "0.29.1"; import pypdf, pypdfium2, docx, openpyxl, psutil; import importlib.metadata as m; from sentence_transformers import SentenceTransformer; from transformers.models.embedding_gemma2.processing_embedding_gemma2 import EmbeddingGemma2Processor; '+REQUIREMENTS.map(item=>{const [name,version]=item.split('==');return `assert m.version(${JSON.stringify(name)}) == ${JSON.stringify(version)}`;}).join('; ');
  const modelCheck='from huggingface_hub import snapshot_download; from pathlib import Path; p=Path(snapshot_download("google/embeddinggemma-2", revision="914f7f89142e33e77833254d9c9b90c3cef7303b", local_files_only=True)); assert all((p/f).is_file() for f in ["model.safetensors","modules.json","tokenizer.json","processor_config.json","preprocessor_config.json","config.json","1_Pooling/config.json"]), "Local model cache is incomplete"';
  async function ensureReady(){if(closed)throw Error('Pigeon is closing');if(healthyPython===runtimePython())return;setup();await setupPromise;if(healthyPython!==runtimePython())throw Error(status.error||'Local semantic engine preparation failed');}
  function setup(){if(setupPromise)return snapshot();killEngine('Checking runtime before semantic work');publish({state:'setup',error:'',detail:'Checking the local engine. Missing components are prepared automatically; portfolio files stay on this computer.'});
    setupPromise=(async()=>{let python=runtimePython(),healthy=false;
      if(fs.existsSync(python))try{await runSetupCommand(python,['-c',dependencyCheck],{quiet:true,timeout:30000});healthy=true;}catch{}
      if(!healthy){
        publish({state:'setup',detail:'Preparing the private Python runtime…'});
        const uvCandidates=['uv',path.join(os.homedir(),'.local','bin',process.platform==='win32'?'uv.exe':'uv')];let uv='';for(const candidate of uvCandidates)try{await new Promise((resolve,reject)=>execFile(candidate,['--version'],{timeout:3000},error=>error?reject(error):resolve()));uv=candidate;break;}catch{}
        if(!uv)throw Error('Automatic preparation needs uv (https://docs.astral.sh/uv/). Install uv and try your search again.');
        // Reuse partially installed environments so interrupted preparation can recover.
        python=path.join(managed,process.platform==='win32'?'Scripts/python.exe':'bin/python');
        if(!fs.existsSync(python))await runSetupCommand(uv,['venv','--python','3.12',managed]);
        await runSetupCommand(uv,['pip','install','--python',python,'torch==2.14.1','torchvision==0.29.1','--index-url','https://download.pytorch.org/whl/cpu']);await runSetupCommand(uv,['pip','install','--python',python,...REQUIREMENTS]);
      }
      let cached=false;try{await runSetupCommand(python,['-c',modelCheck],{quiet:true,timeout:30000});cached=true;}catch{}
      if(!cached){publish({state:'setup',detail:'Downloading the local embedding model. Portfolio files are never uploaded.'});await runSetupCommand(python,['-c','from huggingface_hub import snapshot_download; snapshot_download("google/embeddinggemma-2", revision="914f7f89142e33e77833254d9c9b90c3cef7303b", max_workers=1)']);await runSetupCommand(python,['-c',modelCheck],{quiet:true,timeout:30000});}
      await fsp.mkdir(userData,{recursive:true});await fsp.writeFile(globalConfig,JSON.stringify({python}));runtimeOverride=python;healthyPython=python;setupRetryAfter=0;killEngine('Runtime prepared');publish({state:paused?'paused':'waiting',error:'',waitReason:null,detail:manual?'Engine ready. Starting your requested analysis now.':`Engine ready. Automatic analysis starts after ${idleMinutes()} minutes of inactivity.`});
    })().catch(error=>{healthyPython='';setupRetryAfter=Date.now()+60000;publish({state:'error',error:error.message,detail:'Automatic preparation could not finish. The next search will retry.'});throw error;}).finally(()=>{setupPromise=null;});setupPromise.catch(()=>{});return snapshot();}
  function stop(){if(contextKey)persistChanges();epoch++;paused=true;clearTimeout(syncTimer);syncTimer=null;pendingSync.clear();dirtyAssets.clear();knownFingerprints.clear();killEngine('Portfolio work stopped');contextKey='';}
  function close(){if(contextKey&&dirtyAssets.size)persistChanges();closed=true;clearTimeout(syncTimer);clearInterval(ticker);clearInterval(heartbeat);stop();if(setupScope)execFile('systemctl',['--user','kill','--signal=SIGKILL',setupScope],{timeout:3000},()=>{});setupChild?.kill();}
  return{getStatus,peekStatus:()=>({...status,...info,paused,mode:manual?'manual':'automatic',resourcePercent:settings.resourcePercent??15,pauseOnActivity:settings.pauseOnActivity!==false,portfolioId:contextKey?JSON.parse(contextKey)[0]:null}),configure,start,pause,continueAnalysis,assetsChanged,search,setup,stop,close,assetRecord,runtimePython};
}
module.exports={createSemanticService};
