(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.PigeonAssetIndexes=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const normalize=(value)=>String(value||'').toLowerCase();
  const addTo=(map,key,id)=>{if(key===null||key===undefined||key==='')return;let set=map.get(key);if(!set)map.set(key,set=new Set());set.add(id);};
  const removeFrom=(map,key,id)=>{const set=map.get(key);if(!set)return;set.delete(id);if(!set.size)map.delete(key);};
  const increment=(map,key,amount)=>{if(key===null||key===undefined||key==='')return;const next=(map.get(key)||0)+amount;if(next>0)map.set(key,next);else map.delete(key);};
  function create(){
    const records=new Map(),byKind=new Map(),byLocation=new Map(),byCollection=new Map(),byTag=new Map(),byRating=new Map(),favorite=new Set(),deleted=new Set(),offline=new Set(),offlineByLocation=new Map(),contentGroups=new Map(),duplicateHashes=new Set(),duplicateIds=new Set(),visibleCollectionCounts=new Map(),visibleTagCounts=new Map(),visibleTagNames=new Map(),counts={visible:0,uncategorized:0,untagged:0,favorites:0,offline:0,trash:0};
    const derive=(asset)=>{const tags=[...new Map((asset.tags||[]).map((tag)=>[normalize(tag),String(tag)])).entries()].filter(([key])=>key);return{id:asset.id,kind:asset.kind||'',locationId:asset.locationId||'',collections:[...new Set(asset.collectionIds||[])],tags:tags.map(([key])=>key),tagNames:Object.fromEntries(tags),rating:Number(asset.rating)||0,favorite:Boolean(asset.favorite),deleted:Boolean(asset.deletedAt),locked:Boolean(asset.locked),offline:Boolean(asset.sourceMissing||asset.sourcePending),contentHash:asset.contentHash||'',search:normalize([asset.filename,asset.path,asset.note,...(asset.tags||[])].join(' ')),sort:{name:normalize(asset.name||asset.filename),modified:Number(asset.modified)||0,indexedAt:Number(asset.indexedAt)||0,size:Number(asset.size)||0,dimensions:(Number(asset.width)||0)*(Number(asset.height)||0),rating:Number(asset.rating)||0}};};
    const detachContent=(record)=>{if(!record.contentHash)return;const group=contentGroups.get(record.contentHash);if(!group)return;group.delete(record.id);duplicateIds.delete(record.id);if(group.size===1){duplicateHashes.delete(record.contentHash);duplicateIds.delete(group.values().next().value);}if(!group.size)contentGroups.delete(record.contentHash);};
    const attachContent=(record)=>{if(!record.contentHash)return;let group=contentGroups.get(record.contentHash);if(!group)contentGroups.set(record.contentHash,group=new Set());group.add(record.id);if(group.size>1){duplicateHashes.add(record.contentHash);for(const id of group)duplicateIds.add(id);}};
    const adjustVisible=(record,amount)=>{if(record.deleted||record.locked)return;counts.visible+=amount;if(!record.tags.length){counts.untagged+=amount;if(!record.collections.length)counts.uncategorized+=amount;}if(record.favorite)counts.favorites+=amount;for(const key of record.collections)increment(visibleCollectionCounts,key,amount);for(const key of record.tags){increment(visibleTagCounts,key,amount);if(amount>0)visibleTagNames.set(key,record.tagNames[key]||key);else if(!visibleTagCounts.has(key))visibleTagNames.delete(key);}};
    const detach=(record)=>{if(!record)return;removeFrom(byKind,record.kind,record.id);removeFrom(byLocation,record.locationId,record.id);for(const key of record.collections)removeFrom(byCollection,key,record.id);for(const key of record.tags)removeFrom(byTag,key,record.id);removeFrom(byRating,record.rating,record.id);favorite.delete(record.id);deleted.delete(record.id);offline.delete(record.id);if(record.deleted)counts.trash-=1;if(record.offline){counts.offline-=1;increment(offlineByLocation,record.locationId,-1);}adjustVisible(record,-1);detachContent(record);};
    const upsert=(asset)=>{if(!asset?.id)return;detach(records.get(asset.id));const record=derive(asset);records.set(asset.id,record);addTo(byKind,record.kind,record.id);addTo(byLocation,record.locationId,record.id);for(const key of record.collections)addTo(byCollection,key,record.id);for(const key of record.tags)addTo(byTag,key,record.id);addTo(byRating,record.rating,record.id);if(record.favorite)favorite.add(record.id);if(record.deleted){deleted.add(record.id);counts.trash+=1;}if(record.offline){offline.add(record.id);counts.offline+=1;increment(offlineByLocation,record.locationId,1);}adjustVisible(record,1);attachContent(record);};
    const reset=(assets=[])=>{records.clear();byKind.clear();byLocation.clear();byCollection.clear();byTag.clear();byRating.clear();favorite.clear();deleted.clear();offline.clear();offlineByLocation.clear();contentGroups.clear();duplicateHashes.clear();duplicateIds.clear();visibleCollectionCounts.clear();visibleTagCounts.clear();visibleTagNames.clear();Object.assign(counts,{visible:0,uncategorized:0,untagged:0,favorites:0,offline:0,trash:0});for(const asset of assets)upsert(asset);};
    const remove=(id)=>{detach(records.get(id));records.delete(id);};
    const searchMatches=(asset,query)=>!query||records.get(asset.id)?.search.includes(normalize(query))||false;
    const sortValue=(asset,field)=>records.get(asset.id)?.sort[field]??(field==='name'?normalize(asset.name||asset.filename):Number(asset[field])||0);
    const summary=()=>({...counts,tagCount:visibleTagCounts.size,collectionCounts:new Map(visibleCollectionCounts)});
    const allTags=()=>[...visibleTagNames.values()].sort((a,b)=>a.localeCompare(b,undefined,{sensitivity:'base'}));
    const tagCatalog=()=>[...visibleTagCounts].map(([key,count])=>({name:visibleTagNames.get(key)||key,count})).sort((a,b)=>a.name.localeCompare(b.name,undefined,{sensitivity:'base'}));
    const duplicateGroups=()=>[...duplicateHashes].map((hash)=>[...contentGroups.get(hash)]);
    const offlineCount=(locationIds=[])=>counts.offline+[...locationIds].reduce((total,id)=>total+Math.max(0,(byLocation.get(id)?.size||0)-(offlineByLocation.get(id)||0)),0);
    const snapshot=()=>({size:records.size,byKind,byLocation,byCollection,byTag,byRating,favorite,deleted,offline,offlineByLocation,contentGroups,duplicateHashes,duplicateIds,visibleCollectionCounts,visibleTagCounts});
    return{reset,upsert,remove,searchMatches,sortValue,summary,allTags,tagCatalog,duplicateGroups,offlineCount,snapshot};
  }
  return{create};
});
