(() => {
  'use strict';
  const api=window.pigeon,dialog=document.querySelector('#semantic-panel');if(!api?.semanticStatus||!dialog)return;
  dialog.innerHTML=`<header><div><h2>✦ Semantic search</h2><p>Find files by meaning, or use a file as your example.</p></div><button type="button" data-semantic="close" aria-label="Close semantic search">✕</button></header>
  <form id="semantic-form"><label for="semantic-query">What would you like to find?</label><div class="semantic-query-row"><input id="semantic-query" type="search" placeholder="Describe an image, scene or idea…" maxlength="4000" autocomplete="off"><button type="submit" id="semantic-run">⌕ Search</button></div>
  <details class="semantic-section"><summary>▣ Search with an example</summary><div class="semantic-sample-row"><button type="button" data-semantic="choose">▧ Choose file</button><button type="button" data-semantic="selected">◎ Use selected</button><span id="semantic-sample">Or drop a file into this panel.</span><button type="button" data-semantic="clear-sample" hidden>✕ Clear example</button></div></details>
  <details class="semantic-section"><summary>☷ Refine results</summary><div class="semantic-options"><label>Similarity <input id="semantic-minimum" type="range" min="0" max="95" value="55"><output id="semantic-threshold">0.55</output></label><label>Result limit <select id="semantic-limit"><option>50</option><option selected>200</option><option>500</option><option>1000</option></select></label><label>File type <select id="semantic-kind"><option value="">All types</option><option value="image">Images</option><option value="video">Videos</option><option value="audio">Audio</option><option value="document">Documents</option><option value="file">Other files</option></select></label></div></details></form>
  <div id="semantic-search-progress" class="semantic-progress hidden" role="progressbar" aria-label="Semantic search progress" aria-valuemin="0" aria-valuemax="100"><i></i><span>Preparing search…</span></div><small id="semantic-search-time" class="hidden"></small><p id="semantic-summary" role="status" aria-live="polite">Search results open in the Semantic tab. Your files stay in their own tab.</p>
  <section class="semantic-engine-controls"><h3>◴ Library analysis</h3><strong id="semantic-state">Checking local engine…</strong><div id="semantic-progress" class="semantic-progress" role="progressbar" aria-label="Library analysis progress" aria-valuemin="0" aria-valuemax="100"><i></i><span>0%</span></div><small id="semantic-scan-count"></small><div class="semantic-actions"><button type="button" data-semantic="start">▶ Analyze now</button><button type="button" data-semantic="pause">Ⅱ Pause</button><label><input id="semantic-auto" type="checkbox" checked> Continue automatically when idle</label></div><label class="semantic-resource-control" for="semantic-resource-limit">Resource limit <output id="semantic-resource-value">15%</output><input id="semantic-resource-limit" type="range" min="5" max="50" step="1" value="15"></label><small>CPU and memory share this limit. Lower is quieter; higher is faster. Completed work is saved and resumes when you reopen Pigeon.</small><details class="semantic-section"><summary>ⓘ Activity & technical details</summary><p id="semantic-detail" role="status"></p><small id="semantic-resource"></small><p>Linux enforces worker CPU and memory limits. Other systems use cooperative CPU limits and memory monitoring. A limit too low to load the model stops analysis safely.</p></details></section>`;
  const bar=document.createElement('section');bar.id='semantic-results-bar';bar.className='semantic-results-bar hidden';bar.innerHTML='<div><strong>Semantic search results</strong><p id="semantic-results-summary" role="status"></p></div><button type="button" id="semantic-more" hidden>Load more</button><button type="button" data-semantic-exit>Files tab</button>';document.querySelector('#asset-grid').before(bar);
  const tabs=document.createElement('nav');tabs.className='semantic-view-tabs';tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','Thumbnail views');tabs.innerHTML='<button type="button" role="tab" aria-selected="true" data-thumbnail-tab="files">▱ Files</button><button type="button" role="tab" aria-selected="false" data-thumbnail-tab="semantic" disabled>✦ Semantic</button>';document.querySelector('.toolbar-center').append(tabs);
  const $=id=>dialog.querySelector('#'+id),more=bar.querySelector('#semantic-more');
  let sample=null,results=[],generation=0,portfolio=null,timer=null,busy=false,lastStatus=null,lastRequest=null,filesView=null,semanticView=null,searchStarted=0,searchTimer=null;
  const message=value=>{$('semantic-summary').textContent=String(value);bar.querySelector('#semantic-results-summary').textContent=String(value);};
  function saveView(){return {...captureNavigationSnapshot(),selectedId:state.selectedId,selectedIds:[...state.selectedIds],includeSubfolderContent:state.includeSubfolderContent,showCheckedOnly:state.showCheckedOnly,similarIds:state.similarIds?[...state.similarIds]:null};}
  function restoreSelection(saved){if(!saved)return;state.selectedIds=new Set(saved.selectedIds.filter(id=>assetById(id)));state.selectedId=assetById(saved.selectedId)?saved.selectedId:null;updateCardSelectionStyles();renderInspector();}
  function syncTabs(){const active=state.view==='semantic';for(const button of tabs.children)button.setAttribute('aria-selected',String((button.dataset.thumbnailTab==='semantic')===active));if(!active)tabs.children[0].textContent='▱ '+(elements.title.textContent||'Files');}
  function showTab(name){if(name==='files'&&state.view==='semantic'&&filesView){semanticView=saveView();hideInternalViewer();state.includeSubfolderContent=filesView.includeSubfolderContent;state.showCheckedOnly=filesView.showCheckedOnly;state.similarIds=filesView.similarIds?new Set(filesView.similarIds):null;applyNavigationSnapshot(filesView);restoreSelection(filesView);}else if(name==='semantic'&&state.view!=='semantic'&&lastRequest){filesView=saveView();selectView('semantic','Semantic');if(semanticView){scheduleGridScrollRestore(semanticView.gridScrollTop);restoreSelection(semanticView);}}syncTabs();decorateResults();}
  tabs.addEventListener('click',event=>{const button=event.target.closest('[data-thumbnail-tab]');if(button)showTab(button.dataset.thumbnailTab);});bar.querySelector('[data-semantic-exit]').addEventListener('click',()=>showTab('files'));
  function sampleLabel(){ $('semantic-sample').textContent=sample?`Example: ${sample.name||sample.path||sample.assetId}`:'Or drop a file into this panel.';dialog.querySelector('[data-semantic="clear-sample"]').hidden=!sample;}
  function resetPortfolio(id){if(portfolio===id)return;portfolio=id;generation++;sample=null;results=[];lastRequest=null;filesView=null;semanticView=null;tabs.children[1].disabled=true;more.hidden=true;sampleLabel();if(state.view==='semantic')selectView('all','All');message('Search this portfolio by description or example.');}
  function progress(element,percent,label){element.style.setProperty('--progress',percent+'%');element.querySelector('span').textContent=label;element.setAttribute('aria-valuenow',String(percent));}
  function searchProgress(){if(!busy)return;const p=lastStatus?.searchProgress,elapsed=Math.max(0,(Date.now()-searchStarted)/1000),determinate=p?.total>0,percent=determinate?Math.min(100,Math.round(p.completed/p.total*100)):0;const host=$('semantic-search-progress');host.classList.toggle('indeterminate',!determinate);progress(host,percent,determinate?`${percent}% · Comparing matches`:p?.stage||'Preparing search…');if(!determinate)host.removeAttribute('aria-valuenow');const remaining=determinate&&p.completed>0?Math.ceil(elapsed*(p.total-p.completed)/p.completed):null;$('semantic-search-time').textContent=`${Math.floor(elapsed)}s elapsed${remaining!==null?` · about ${remaining}s remaining`:' · Time remaining will be estimated when comparison starts'}`;}
  function updateStatus(status){if(!status)return;lastStatus=status;resetPortfolio(status.portfolioId);$('semantic-state').textContent=`${status.state==='idle'?'Ready':status.paused?'Paused':status.state==='indexing'?'Analyzing files':status.state==='waiting'?'Waiting for available resources':status.state} · ${status.indexed||0} indexed`;$('semantic-detail').textContent=[status.detail,status.current?'Current: '+status.current:'',status.error].filter(Boolean).join(' — ');const r=status.resources||{};$('semantic-resource').textContent=`CPU ${r.cpuPercent??0}% · Memory ${((r.memoryBytes||0)/1024/1024).toFixed(0)} MB${status.hardCaps?' · Kernel limits active':''}`;const total=status.total||0,completed=Math.min(total,status.completed||0),percent=total?Math.round(completed/total*100):0;progress($('semantic-progress'),percent,percent+'%');$('semantic-scan-count').textContent=`${completed.toLocaleString()} / ${total.toLocaleString()} files${status.limited?` · ${status.limited} with content limits`:''}`;$('semantic-auto').checked=status.automatic;dialog.querySelector('[data-semantic="pause"]').textContent=status.paused?'▶ Resume':'Ⅱ Pause';if(document.activeElement!==$('semantic-resource-limit'))$('semantic-resource-limit').value=status.resourcePercent??15;$('semantic-resource-value').textContent=$('semantic-resource-limit').value+'%';searchProgress();}
  async function refresh(){try{updateStatus(await api.semanticStatus());}catch(error){$('semantic-detail').textContent=error.message;}}
  function panelVisible(){return !dialog.classList.contains('hidden')&&!document.querySelector('#inspector').classList.contains('hidden-panel');}
  async function open(){const anchor=captureVirtualLayoutAnchor();document.querySelector('#inspector').classList.remove('hidden-panel');document.querySelector('#inspector-toggle').classList.add('selected');selectRightPanelTab('semantic');scheduleVirtualLayoutRefresh(anchor);await refresh();$('semantic-query').focus();}
  function rankedAssets(){if(portfolio!==state.library.activePortfolioId)return[];return results.map(r=>assetById(r.id)).filter(a=>a&&!a.locked&&!a.deletedAt&&!a.encrypted&&!a.sourceMissing&&!a.sourcePending);}
  function renderResults(){invalidateAssetViewCache();tabs.children[1].disabled=false;if(state.view!=='semantic'){filesView=saveView();selectView('semantic','Semantic');}else renderGrid();semanticView=null;syncTabs();}
  function decorateResults(){const active=state.view==='semantic';bar.classList.toggle('hidden',!active);syncTabs();const byId=new Map(active?results.map(r=>[r.id,r]):[]);for(const card of document.querySelectorAll('#asset-grid .asset-card')){const result=byId.get(card.dataset.assetId),old=card.querySelector('.semantic-match-badge');if(!result){old?.remove();card.querySelector('.semantic-match-range')?.remove();delete card.dataset.semanticStart;delete card.dataset.semanticEnd;card._semanticLoopActive=false;continue;}let badge=old;if(!badge){badge=document.createElement('span');badge.className='semantic-match-badge';card.querySelector('.asset-preview')?.append(badge);}const text=`Similarity ${result.score.toFixed(3)} · ${result.match?.label||'Content match'}`;if(badge.textContent!==text)badge.textContent=text;badge.title=result.match?.snippet||text;const asset=assetById(result.id),start=Number(result.match?.start),end=Number(result.match?.end),duration=Number(asset?.duration);if(asset?.kind==='video'&&Number.isFinite(start)&&Number.isFinite(end)&&end>start&&duration>0&&start<duration){card.dataset.semanticStart=String(start);card.dataset.semanticEnd=String(Math.min(duration,end));let range=card.querySelector('.semantic-match-range');if(!range){range=document.createElement('div');range.className='semantic-match-range';range.innerHTML='<i></i><span></span><i></i>';card.querySelector('.asset-preview').append(range);}range.title=`Match ${formatMediaTime(start)}–${formatMediaTime(end)} · Hover between markers to loop`;range.style.setProperty('--match-start',Math.max(0,start/duration*100)+'%');range.style.setProperty('--match-width',Math.min(duration-start,end-start)/duration*100+'%');}}}
  const observer=new MutationObserver(decorateResults);observer.observe(document.querySelector('#asset-grid'),{childList:true,subtree:true});observer.observe(document.querySelector('#view-title'),{childList:true,subtree:true});
  async function runSearch(append=false){if(busy)return;const query=$('semantic-query').value.trim();if(!query&&!sample){message('Describe what you need or choose an example file.');return;}const token=++generation;busy=true;searchStarted=Date.now();lastStatus={...lastStatus,searchProgress:null};$('semantic-run').disabled=true;$('semantic-search-progress').classList.remove('hidden');$('semantic-search-time').classList.remove('hidden');searchProgress();searchTimer=setInterval(searchProgress,250);message('Searching locally…');try{const request=append?{...lastRequest,offset:results.length}:{query,...(query?{}:sample?.assetId?{assetId:sample.assetId}:{samplePath:sample?.path}),minimum:Number($('semantic-minimum').value)/100,limit:Number($('semantic-limit').value),kind:$('semantic-kind').value};const response=await api.semanticSearch(request);if(token!==generation)return;lastRequest=request;results=append?[...results,...response.results]:response.results;more.hidden=results.length>=response.totalMatches;renderResults();message(`${response.totalMatches} matches · showing ${results.length}. ${response.indexed} files analyzed.`);progress($('semantic-search-progress'),100,'100% · Search complete');$('semantic-search-time').textContent=`Completed in ${((Date.now()-searchStarted)/1000).toFixed(1)}s`;}catch(error){if(token===generation){message(error.message);$('semantic-search-progress').classList.add('hidden');$('semantic-search-time').textContent='Search stopped';}}finally{busy=false;clearInterval(searchTimer);$('semantic-search-progress').classList.remove('indeterminate');$('semantic-run').disabled=false;}}
  async function action(name){try{if(name==='close'){selectRightPanelTab('details');return;}if(name==='start'){const scope=state.view==='semantic'&&filesView?filesView:state;const selected=scope.collectionId?{type:'collection',id:scope.collectionId}:scope.smartFolderId?{type:'smart-folder',id:scope.smartFolderId}:scope.locationId?{type:'folder',id:scope.locationId,subfolder:scope.locationSubfolder}:null;updateStatus(await api.semanticStart({portfolioId:state.library.activePortfolioId,scope:selected,includeSubfolders:scope.includeSubfolderContent}));return;}if(name==='pause'){updateStatus(await api.semanticPause(!lastStatus?.paused));return;}if(name==='choose'){const selected=await api.semanticChooseSample();if(selected){sample=selected;$('semantic-query').value='';sampleLabel();}return;}if(name==='selected'){const asset=assetById(state.selectedId);if(!asset||asset.locked){message('Select an accessible file first.');return;}sample={assetId:asset.id,name:asset.name||asset.filename};$('semantic-query').value='';sampleLabel();return;}if(name==='clear-sample'){sample=null;sampleLabel();}}catch(error){message(error.message);}}
  dialog.addEventListener('click',event=>{const control=event.target.closest('[data-semantic]');if(control)void action(control.dataset.semantic);});dialog.addEventListener('dragover',event=>{event.preventDefault();event.stopPropagation();dialog.classList.add('semantic-drag');});dialog.addEventListener('dragleave',()=>dialog.classList.remove('semantic-drag'));dialog.addEventListener('drop',event=>{event.preventDefault();event.stopPropagation();dialog.classList.remove('semantic-drag');const file=event.dataTransfer.files[0];if(!file)return;const path=api.pathForDroppedFile(file);if(!path){message('Use Choose file to select this example.');return;}sample={path,name:file.name};$('semantic-query').value='';dialog.querySelector('details').open=true;sampleLabel();});
  $('semantic-form').addEventListener('submit',event=>{event.preventDefault();void runSearch();});$('semantic-minimum').addEventListener('input',()=>{$('semantic-threshold').textContent=(Number($('semantic-minimum').value)/100).toFixed(2);});$('semantic-kind').addEventListener('change',()=>{if(lastRequest)void runSearch();});more.addEventListener('click',()=>void runSearch(true));$('semantic-auto').addEventListener('change',async()=>{try{updateStatus(await api.semanticConfigure({automatic:$('semantic-auto').checked}));}catch(error){message(error.message);}});$('semantic-resource-limit').addEventListener('input',()=>{$('semantic-resource-value').textContent=$('semantic-resource-limit').value+'%';});$('semantic-resource-limit').addEventListener('change',async()=>{try{updateStatus(await api.semanticConfigure({resourcePercent:Number($('semantic-resource-limit').value)}));}catch(error){message(error.message);}});
  document.addEventListener('pigeon:right-panel-tab',event=>{clearInterval(timer);timer=null;if(event.detail==='semantic'){void refresh();timer=setInterval(refresh,3000);}});api.onSemanticStatus(status=>{if(panelVisible()||busy||state.view==='semantic')updateStatus(status);});
  document.querySelector('#asset-grid').addEventListener('dblclick',event=>{const result=results.find(r=>r.id===event.target.closest('[data-asset-id]')?.dataset.assetId);if(state.view==='semantic'&&result?.match?.start!=null){const asset=assetById(result.id),media=asset?.kind==='video'?document.querySelector('#viewer-video'):asset?.kind==='audio'?document.querySelector('#viewer-audio'):null;if(!media)return;const seek=()=>{media.currentTime=result.match.start;};if(media.readyState>=1)seek();else media.addEventListener('loadedmetadata',seek,{once:true});}});
  document.querySelector('#semantic-search-button')?.addEventListener('click',()=>void open());document.querySelector('#semantic-sample-button')?.addEventListener('click',async()=>{await open();dialog.querySelector('details').open=true;await action('choose');});
  window.pigeonSemanticSearch={open,assets:rankedAssets,searchSelected:async()=>{await open();dialog.querySelector('details').open=true;await action('selected');},hoverTime(card,ratio,duration,pointerX=null){const start=Number(card.dataset.semanticStart),end=Number(card.dataset.semanticEnd),time=duration*ratio,bounds=card.querySelector('.semantic-match-range')?.getBoundingClientRect(),insideMarker=Number.isFinite(pointerX)&&bounds&&pointerX>=bounds.left&&pointerX<=bounds.right;if(state.view==='semantic'&&card.dataset.semanticStart!==undefined&&end>start&&((time>=start&&time<=end)||insideMarker)){const first=!card._semanticLoopActive;card._semanticLoopActive=true;return first?start:null;}card._semanticLoopActive=false;return time;}};
})();
