(() => {
  'use strict';
  const api=window.pigeon;if(!api?.semanticStatus)return;
  const dialog=document.querySelector('#semantic-panel');if(!dialog)return;
  dialog.innerHTML=`<header><div><h2>Semantic search</h2><p>Find related images, videos, audio and documents in the active portfolio.</p></div><button type="button" data-semantic="close" aria-label="Close semantic search">✕</button></header>
  <section class="semantic-engine-controls"><div><strong id="semantic-state">Checking local engine…</strong><p id="semantic-detail" role="status" aria-live="polite"></p><small id="semantic-resource"></small></div><div class="semantic-actions"><button type="button" data-semantic="start">Analyze now</button><button type="button" data-semantic="pause">Pause</button><label><input id="semantic-auto" type="checkbox" checked> Analyze automatically when compute use is low</label></div><progress id="semantic-progress" max="1" value="0"></progress><small>Automatic analysis: 12% CPU / memory budgets. Analyze now: 18%. CPU only; pauses under load. Linux enforces CPU and memory limits; elsewhere memory monitoring stops work at the budget. Brief CPU sampling spikes are possible.</small></section>
  <form id="semantic-form"><label for="semantic-query">Describe what you are looking for</label><div class="semantic-query-row"><input id="semantic-query" type="search" placeholder="e.g. a bird flying over rooftops" maxlength="4000" autocomplete="off"><button type="submit" id="semantic-run">Search</button></div><div class="semantic-sample-row"><button type="button" data-semantic="choose">Choose sample file…</button><button type="button" data-semantic="selected">Use selected asset</button><span id="semantic-sample">Or drop an image, video, audio file or document here.</span><button type="button" data-semantic="clear-sample" hidden>Clear sample</button></div><div class="semantic-options"><label>Minimum similarity <input id="semantic-minimum" type="range" min="0" max="95" step="1" value="55"><output id="semantic-threshold">0.55</output></label><label>Maximum results <select id="semantic-limit"><option>50</option><option selected>200</option><option>500</option><option>1000</option></select></label><label>Type <select id="semantic-kind"><option value="">All types</option><option value="image">Images</option><option value="video">Videos</option><option value="audio">Audio</option><option value="document">Documents</option><option value="file">Other files</option></select></label></div></form>
  <p id="semantic-summary" role="status" aria-live="polite">Results are ranked by meaning. Similarity scores are not confidence percentages.</p>`;
  dialog.append(dialog.querySelector('.semantic-engine-controls'));
  const resultBar=document.createElement('section');resultBar.id='semantic-results-bar';resultBar.className='semantic-results-bar hidden';resultBar.innerHTML='<div><strong>Semantic search results</strong><p id="semantic-results-summary" role="status" aria-live="polite"></p></div><button type="button" id="semantic-more" hidden>Load more matches</button><button type="button" data-semantic-exit>Back to files</button>';document.querySelector('#asset-grid').before(resultBar);
  const more=resultBar.querySelector('#semantic-more');
  let sample=null,results=[],generation=0,portfolio=null,timer=null,busy=false,lastStatus=null,lastRequest=null;
  const $=id=>dialog.querySelector('#'+id);
  const message=value=>{$('semantic-summary').textContent=String(value);resultBar.querySelector('#semantic-results-summary').textContent=String(value);};
  function resetPortfolio(id){if(portfolio===id)return;portfolio=id;generation++;sample=null;results=[];lastRequest=null;more.hidden=true;sampleLabel();if(typeof state!=='undefined'&&state.view==='semantic'){invalidateAssetViewCache();renderGrid();}message('Search the active portfolio. Files must be analyzed before their content appears here.');}
  function sampleLabel(){ $('semantic-sample').textContent=sample?`Sample: ${sample.name||sample.path||sample.assetId}`:'Or drop an image, video, audio file or document here.';dialog.querySelector('[data-semantic="clear-sample"]').hidden=!sample;}
  function updateStatus(status){if(!status)return;lastStatus=status;resetPortfolio(status.portfolioId);$('semantic-state').textContent=`${status.model} · ${status.state} · ${status.indexed||0} indexed${status.limited?` · ${status.limited} with content limits`:''}`;$('semantic-detail').textContent=[status.detail,status.current?`${status.activeFiles?.length>1?'Current batch':'Current file'}: ${status.current}`:'',status.error].filter(Boolean).join(' — ');const r=status.resources||{};$('semantic-resource').textContent=`System CPU ${status.systemCpuPercent??0}% · Engine CPU ${r.cpuPercent??0}% · Engine memory ${((r.memoryBytes||0)/1024/1024).toFixed(0)} MB${r.memoryLimitBytes?` / ${(r.memoryLimitBytes/1024/1024).toFixed(0)} MB`:''}${status.hardCaps?' · Kernel limits active':''}${status.fileWorkers?` · ${status.fileWorkers} file workers`:''}`;$('semantic-progress').max=Math.max(1,status.total||1);$('semantic-progress').value=status.completed||0;$('semantic-auto').checked=status.automatic;dialog.querySelector('[data-semantic="pause"]').textContent=status.paused?'Resume':'Pause';}
  async function refresh(){try{updateStatus(await api.semanticStatus());}catch(error){$('semantic-detail').textContent=error.message;}}
  function panelVisible(){return !dialog.classList.contains('hidden')&&!document.querySelector('#inspector').classList.contains('hidden-panel');}
  async function open(){const anchor=captureVirtualLayoutAnchor();document.querySelector('#inspector').classList.remove('hidden-panel');document.querySelector('#inspector-toggle').classList.add('selected');selectRightPanelTab('semantic');scheduleVirtualLayoutRefresh(anchor);await refresh();$('semantic-query').focus();}
  function rankedAssets(){if(typeof state==='undefined'||portfolio!==state.library.activePortfolioId)return[];return results.map(r=>assetById(r.id)).filter(a=>a&&!a.locked&&!a.deletedAt&&!a.encrypted&&!a.sourceMissing&&!a.sourcePending);}
  function renderResults(){invalidateAssetViewCache();if(state.view!=='semantic')selectView('semantic','Semantic search');else renderGrid();}
  function decorateResults(){const active=typeof state!=='undefined'&&state.view==='semantic';resultBar.classList.toggle('hidden',!active);const byId=new Map(active?results.map(r=>[r.id,r]):[]);for(const card of document.querySelectorAll('#asset-grid .asset-card')){const result=byId.get(card.dataset.assetId),old=card.querySelector('.semantic-match-badge');if(!result){old?.remove();continue;}let badge=old;if(!badge){badge=document.createElement('span');badge.className='semantic-match-badge';card.querySelector('.asset-preview')?.append(badge);}const text=`Similarity ${result.score.toFixed(3)} · ${result.match?.label||'Content match'}`;if(badge.textContent!==text)badge.textContent=text;badge.title=result.match?.snippet||text;card.dataset.semanticResult='true';}}
  const observer=new MutationObserver(decorateResults);observer.observe(document.querySelector('#asset-grid'),{childList:true,subtree:true});observer.observe(document.querySelector('#view-title')||document.querySelector('main'),{childList:true,subtree:true});
  async function runSearch(append=false){if(busy)return;const query=$('semantic-query').value.trim();if(!query&&!sample){message('Enter a description or choose a sample file.');return;}const token=++generation;busy=true;$('semantic-run').disabled=true;message('Searching locally…');try{const request=append?{...lastRequest,offset:results.length}:{query,...(query?{}:sample?.assetId?{assetId:sample.assetId}:{samplePath:sample?.path}),minimum:Number($('semantic-minimum').value)/100,limit:Number($('semantic-limit').value),kind:$('semantic-kind').value};lastRequest=request;const response=await api.semanticSearch(request);if(token!==generation)return;results=append?[...results,...response.results]:response.results;more.hidden=results.length>=response.totalMatches;renderResults();message(`${response.totalMatches} matches · showing ${results.length}${response.totalMatches>results.length?' (load more matches below)':''}. ${response.indexed} files analyzed. ${results.length?'Select a thumbnail to inspect it; double-click to open.':'Analyze the portfolio or lower the minimum similarity.'}`);}catch(error){if(token===generation)message(error.message);}finally{busy=false;$('semantic-run').disabled=false;}}
  async function action(name){try{if(name==='close'){selectRightPanelTab('details');return;}if(name==='start'){updateStatus(await api.semanticStart());return;}if(name==='pause'){updateStatus(await api.semanticPause(!lastStatus?.paused));return;}if(name==='choose'){const selected=await api.semanticChooseSample();if(selected){sample=selected;$('semantic-query').value='';sampleLabel();}return;}if(name==='selected'){const asset=typeof state!=='undefined'?assetById(state.selectedId):null;if(!asset||asset.locked){message('Select an accessible asset in Pigeon first.');return;}sample={assetId:asset.id,name:asset.name||asset.filename};$('semantic-query').value='';sampleLabel();return;}if(name==='clear-sample'){sample=null;sampleLabel();}}catch(error){message(error.message);}}
  dialog.addEventListener('click',event=>{const control=event.target.closest('[data-semantic]');if(control)void action(control.dataset.semantic);});
  dialog.addEventListener('dragover',event=>{event.preventDefault();event.stopPropagation();dialog.classList.add('semantic-drag');});dialog.addEventListener('dragleave',()=>dialog.classList.remove('semantic-drag'));dialog.addEventListener('drop',event=>{event.preventDefault();event.stopPropagation();dialog.classList.remove('semantic-drag');const file=event.dataTransfer.files[0];if(!file)return;const path=api.pathForDroppedFile(file);if(!path){message('Could not read the dropped file path. Use Choose sample file.');return;}sample={path,name:file.name};$('semantic-query').value='';sampleLabel();});
  $('semantic-form').addEventListener('submit',event=>{event.preventDefault();void runSearch();});$('semantic-minimum').addEventListener('input',()=>{$('semantic-threshold').textContent=(Number($('semantic-minimum').value)/100).toFixed(2);});$('semantic-kind').addEventListener('change',()=>{if(lastRequest)void runSearch();else renderResults();});more.addEventListener('click',()=>void runSearch(true));$('semantic-auto').addEventListener('change',async()=>{try{updateStatus(await api.semanticConfigure({automatic:$('semantic-auto').checked}));}catch(error){message(error.message);}});
  document.addEventListener('pigeon:right-panel-tab',event=>{clearInterval(timer);timer=null;if(event.detail==='semantic'){void refresh();timer=setInterval(refresh,3000);}});api.onSemanticStatus(status=>{if(panelVisible()||state.view==='semantic')updateStatus(status);});resultBar.querySelector('[data-semantic-exit]').addEventListener('click',()=>selectView('all','All'));
  document.querySelector('#asset-grid').addEventListener('dblclick',event=>{const result=results.find(r=>r.id===event.target.closest('[data-asset-id]')?.dataset.assetId);if(state.view==='semantic'&&result?.match?.start!=null){const media=result.asset.kind==='video'?document.querySelector('#viewer-video'):document.querySelector('#viewer-audio');const seek=()=>{media.currentTime=result.match.start;};if(media.readyState>=1)seek();else media.addEventListener('loadedmetadata',seek,{once:true});}});
  document.querySelector('#semantic-search-button')?.addEventListener('click',()=>void open());document.querySelector('#semantic-sample-button')?.addEventListener('click',async()=>{await open();await action('choose');});
  window.pigeonSemanticSearch={open,assets:rankedAssets,searchSelected:async()=>{await open();await action('selected');}};
})();
