(()=>{
 const selector='.collection-item,#smart-folder-list [data-smart-folder-id]';
 const describe=row=>{const type=row.matches('.collection-item')?'collections':'smartFolders',id=row.dataset.collectionId||row.dataset.smartFolderId;return{type,item:state.library[type]?.find(item=>item.id===id)};};
 const collapseKey=(type,id)=>type==='collections'?collectionCollapseKey(id):smartFolderCollapseKey(id);
 async function create(type,parentId=null){const portfolio=state.library.activePortfolioId,name=await requestText({title:'New Group',label:'Group name',placeholder:'Group name',confirmText:'Create'});if(!name?.trim()||portfolio!==state.library.activePortfolioId)return;const group=await window.pigeon.createSidebarGroup(type,name.trim(),parentId);if(portfolio!==state.library.activePortfolioId)return;if(!state.library[type].some(item=>item.id===group.id))state.library[type].push(group);if(parentId)setFolderCollapsed(collapseKey(type,parentId),false);renderSidebar(false);}
 function menu(event,type,item=null){event.preventDefault();event.stopImmediatePropagation();hideContextMenu();const host=elements.contextMenu;host.innerHTML='';const action=(label,run)=>{const button=document.createElement('button');button.textContent=label;button.addEventListener('click',()=>{hideContextMenu();Promise.resolve().then(run).catch(error=>showToast(error.message));});host.append(button);};action('New '+(item?'Subgroup':'Group')+'…',()=>create(type,item?.id||null));action(type==='collections'?'New Collection…':'New Smart Folder…',()=>{if(item)setFolderCollapsed(collapseKey(type,item.id),false);return type==='collections'?createCollectionPrompt(item?.id||null):openSmartFolderDialog(item?.id||null);});if(item){action('Rename Group…',async()=>{const name=await requestText({title:'Rename Group',label:'Group name',value:item.name,confirmText:'Rename'});if(name?.trim())await(type==='collections'?window.pigeon.renameCollection(item.id,name.trim()):window.pigeon.renameSmartFolder(item.id,name.trim()));});action('Remove Empty Group',async()=>{if(state.library[type].some(child=>child.parentId===item.id)){showToast('Move the contents out of this group before removing it');return;}if(await requestConfirmation({title:'Remove Group?',message:`Remove “${item.name}”? Files on disk will not be deleted.`,confirmText:'Remove'}))await(type==='collections'?window.pigeon.removeCollection(item.id):window.pigeon.removeSmartFolder(item.id));});}host.classList.remove('hidden');positionMenu(host,event.clientX,event.clientY);}
 for(const [section,type] of [['collections','collections'],['smart-folders','smartFolders']]){const heading=document.querySelector(`[data-section-toggle="${section}"]`),button=document.createElement('button');button.className='tiny-button';button.title='New group';button.setAttribute('aria-label','New '+(type==='collections'?'collection':'Smart Folder')+' group');button.innerHTML=iconSvg('folder');button.addEventListener('click',event=>{event.stopPropagation();create(type).catch(error=>showToast(error.message));});heading.querySelector('.section-label-actions').prepend(button);heading.addEventListener('contextmenu',event=>menu(event,type),true);}
 document.addEventListener('contextmenu',event=>{const row=event.target.closest(selector);if(!row)return;const {type,item}=describe(row);if(item?.isGroup)menu(event,type,item);},true);
 document.addEventListener('click',event=>{const row=event.target.closest(selector);if(!row||event.ctrlKey||event.metaKey||event.shiftKey||event.target.closest('.folder-tree-toggle'))return;const {type,item}=describe(row);if(!item?.isGroup)return;event.preventDefault();event.stopImmediatePropagation();const key=collapseKey(type,item.id);setFolderCollapsed(key,!isFolderCollapsed(key));renderSidebar(false);},true);
 function decorate(){for(const row of document.querySelectorAll(selector)){const {item}=describe(row);if(!item?.isGroup)continue;if(!row.classList.contains('sidebar-organizing-group'))row.classList.add('sidebar-organizing-group');const count=row.querySelector('small');if(count&&count.textContent!=='Group')count.textContent='Group';}}
 const observer=new MutationObserver(decorate);for(const id of ['collection-list','smart-folder-list'])observer.observe(document.getElementById(id),{childList:true,subtree:true});decorate();
})();
